[build]
  publish = "dist"
  command = "npm run build"

[[edge_functions]]
  path = "/api/iso"
  function = "iso"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"
    Access-Control-Allow-Headers = "*"
    Access-Control-Expose-Headers = "Content-Length, Content-Range, Accept-Ranges"
