import { strict as assert } from 'node:assert';
import { readFile } from 'node:fs/promises';
const source = await readFile(new URL('../src/quiz.ts', import.meta.url), 'utf8');
assert.match(source, /QUESTIONS\.length/);
assert.match(source, /getRandomValues/);
assert.match(source, /session=shuffle\(QUESTIONS\)/);
assert.match(source, /randomDistinctIndices/);
assert.match(source, /command catalog/i);
assert.match(source, /OS and networking/i);
assert.doesNotMatch(source, /What is a primary learning goal for/);
console.log('Quiz quality and randomization checks passed');
