import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';

const telemetry = await readFile('src/v86-telemetry.ts', 'utf8');
const runtime = await readFile('src/main-v86.ts', 'utf8');
const ready = await readFile('src/v86-ready.ts', 'utf8');
const tutor = await readFile('netlify/edge-functions/tutor.ts', 'utf8');
const iso = await readFile('netlify/edge-functions/iso.ts', 'utf8');
const csp = await readFile('netlify.toml', 'utf8');
const integrity = await readFile('src/core/ISOIntegrity.ts', 'utf8');
const artifacts = await readFile('src/core/artifacts.ts', 'utf8');
const quiz = await readFile('quiz/index.html', 'utf8');
const beginner = await readFile('beginner/index.html', 'utf8');
const beginnerCss = await readFile('src/beginner.css', 'utf8');
const vite = await readFile('vite.config.ts', 'utf8');

assert.equal(/window\.V86\s*=/.test(telemetry), false, 'telemetry must not monkey-patch window.V86');
assert.equal(/(?:\:\s*any\b|\bas\s+any\b|<\s*any\s*>)/.test(telemetry), false, 'telemetry must not use any type');
assert.equal(/window\.(?:guest|alpine|release|identity)/i.test(telemetry), false, 'guest identity must not be exposed globally');
assert.equal(/serial0_send/.test(telemetry), false, 'telemetry must not write to the guest serial port');
assert.match(runtime, /attachGuestTelemetry\s*\(\s*vm/);
assert.match(runtime, /telemetryDispose\?\.\(\)/);
assert.match(runtime, /acceptGuestIdentity\s*\(/);
assert.match(runtime, /markReadyIfIdentityVerified\s*\(/);
assert.match(runtime, /autostart:\s*false/);
assert.match(runtime, /waitForV86Loaded\s*\(\s*vm\s*,\s*policy\.policy\.bootTimeoutMs\s*,\s*signal\s*\)/, 'v86 must wait for its emulator-loaded lifecycle event before run()');
assert.ok(runtime.indexOf('waitForV86Loaded') < runtime.indexOf('vm.run?.()'), 'v86 readiness wait must occur before run()');
assert.equal(/autostart:\s*true/.test(runtime), false, 'v86 must not autostart before listeners are installed');
assert.equal(/emulator-ready/.test(runtime), false, 'runtime must not depend on the obsolete emulator-ready marker');
assert.match(runtime, /wait_until_vga_screen_contains/);
assert.match(runtime, /waitForGuestReady/);
assert.match(ready, /AbortSignal/);
assert.match(ready, /abort/);
assert.match(ready, /remove_listener/);
assert.match(ready, /v86 emulator initialization timed out/);
assert.equal(/request\.headers\.get\(['"]x-forwarded-for['"]\)/.test(tutor), false, 'Tutor must not trust client-supplied forwarding headers');
assert.equal(/(?:\:\s*any\b|\bas\s+any\b|<\s*any\s*>)/.test(tutor), false, 'Tutor must not use any type');
assert.match(tutor, /AbortController/);
assert.match(tutor, /MAX_QUESTION_CHARS/);
assert.match(tutor, /MAX_CONTEXT_CHARS/);
assert.match(tutor, /UPSTASH_REDIS_REST_URL/);
assert.match(tutor, /UPSTASH_REDIS_REST_TOKEN/);
assert.match(iso, /content-length/);
assert.match(iso, /source\.size/);
assert.match(iso, /upstream\.body/);
assert.equal(/arrayBuffer\(\)/.test(iso), false, 'ISO edge proxy must not buffer the complete image');
assert.match(iso, /\^bytes=\(\\d\+\)-\(\\d\*\)\$/);
assert.match(artifacts, /size:\s*691011584/);
assert.match(artifacts, /size:\s*51380224/);
assert.match(artifacts, /size:\s*7731200/);
assert.match(integrity, /bytes\.byteLength !== artifact\.size/);
assert.match(integrity, /from ['"]\.\/artifacts\.ts['"]/);
assert.equal(csp.includes('https://router.huggingface.co'), false, 'browser CSP must not allow direct Hugging Face connections');
assert.doesNotMatch(quiz, /<style[\s>]/i, 'quiz must not rely on inline styles under the strict CSP');
assert.doesNotMatch(quiz, /<script(?![^>]+src=)[^>]*>/i, 'quiz must not rely on inline scripts under the strict CSP');
assert.match(quiz, /quiz\/quiz\.css/);
assert.match(quiz, /src\/quiz\.ts/);
assert.match(beginner, /200 Linux Commands/);
assert.match(beginner, /command-catalog-body/);
assert.match(beginnerCss, /max-height:680px/);
assert.match(beginnerCss, /position:sticky/);
assert.match(vite, /login:\s*entry\('login\/index\.html'\)/);
console.log('Static and runtime-facing security guardrails passed');
