export type CommandCategory =
  | 'navigation' | 'files' | 'text' | 'search' | 'shell' | 'permissions'
  | 'users' | 'processes' | 'system' | 'storage' | 'network' | 'archives'
  | 'packages' | 'development' | 'diagnostics' | 'containers' | 'services'
  | 'security' | 'advanced';

export interface LinuxCommandLesson {
  name: string;
  category: CommandCategory;
  summary: string;
  example: string;
}

/**
 * Canonical 200-command curriculum. The catalog is deliberately data-only so
 * the UI, tutor and command explorer can consume the same source of truth.
 * A command is not advertised as executable by Engine A unless the engine
 * explicitly implements its semantics.
 */
export const LINUX_COMMANDS: readonly LinuxCommandLesson[] = [
  ['pwd','navigation','Print the current working directory','pwd'],
  ['ls','navigation','List directory contents','ls -la'],
  ['cd','navigation','Change the working directory','cd /tmp'],
  ['tree','navigation','Display a directory tree','tree /root'],
  ['dirs','navigation','Show the directory stack','dirs'],
  ['pushd','navigation','Push a directory onto the stack','pushd /tmp'],
  ['popd','navigation','Return to the previous stack directory','popd'],
  ['realpath','navigation','Resolve a path to an absolute path','realpath ./notes'],
  ['basename','navigation','Print the final component of a path','basename /var/log/app.log'],
  ['dirname','navigation','Print the directory component of a path','dirname /var/log/app.log'],
  ['touch','files','Create files or update timestamps','touch notes.txt'],
  ['cat','files','Print file contents','cat notes.txt'],
  ['cp','files','Copy files or directories','cp notes.txt backup.txt'],
  ['mv','files','Move or rename files','mv draft.txt final.txt'],
  ['rm','files','Remove files','rm old.txt'],
  ['mkdir','files','Create directories','mkdir -p projects/demo'],
  ['rmdir','files','Remove empty directories','rmdir empty'],
  ['ln','files','Create links','ln -s target link'],
  ['readlink','files','Read a symbolic link','readlink link'],
  ['file','files','Identify a file type','file notes.txt'],
  ['stat','files','Show file metadata','stat notes.txt'],
  ['truncate','files','Change a file size','truncate -s 0 notes.txt'],
  ['install','files','Copy files and set attributes','install -m 644 app.conf /tmp/app.conf'],
  ['mktemp','files','Create a temporary file or directory','mktemp'],
  ['shred','files','Overwrite a file before removal','shred -n 1 sample.txt'],
  ['head','text','Print the beginning of a file','head -n 5 notes.txt'],
  ['tail','text','Print the end of a file','tail -n 5 notes.txt'],
  ['less','text','Read text interactively','less notes.txt'],
  ['more','text','Page through text','more notes.txt'],
  ['nl','text','Number lines','nl notes.txt'],
  ['wc','text','Count lines, words and bytes','wc -l notes.txt'],
  ['cut','text','Extract columns or characters','cut -d: -f1 /etc/passwd'],
  ['paste','text','Merge lines from files','paste first.txt second.txt'],
  ['join','text','Join files on a common field','join users.txt groups.txt'],
  ['expand','text','Convert tabs to spaces','expand notes.txt'],
  ['unexpand','text','Convert spaces to tabs','unexpand notes.txt'],
  ['fold','text','Wrap long lines','fold -w 80 notes.txt'],
  ['fmt','text','Format paragraphs','fmt notes.txt'],
  ['column','text','Format text into columns','column -t data.txt'],
  ['tr','text','Translate or delete characters','tr a-z A-Z < notes.txt'],
  ['rev','text','Reverse characters on each line','rev notes.txt'],
  ['sort','text','Sort lines','sort names.txt'],
  ['uniq','text','Filter adjacent duplicate lines','sort names.txt | uniq'],
  ['comm','text','Compare sorted files','comm a.txt b.txt'],
  ['diff','text','Compare text files','diff old.txt new.txt'],
  ['cmp','text','Compare files byte by byte','cmp a.bin b.bin'],
  ['strings','text','Find printable strings','strings app.bin'],
  ['grep','search','Search text by pattern','grep error app.log'],
  ['egrep','search','Search using extended regular expressions','egrep "warn|error" app.log'],
  ['fgrep','search','Search literal strings','fgrep "[ok]" app.log'],
  ['find','search','Find files by conditions','find /root -name "*.c"'],
  ['locate','search','Find files from a filename database','locate notes.txt'],
  ['which','search','Locate an executable in PATH','which sh'],
  ['whereis','search','Locate binaries, sources and manuals','whereis sh'],
  ['xargs','search','Build commands from standard input','printf "a\nb\n" | xargs echo'],
  ['awk','search','Process structured text','awk "{print $1}" data.txt'],
  ['sed','search','Stream-edit text','sed "s/foo/bar/g" notes.txt'],
  ['rg','search','Fast recursive text search','rg "TODO" .'],
  ['grep','search','Search lines matching a pattern','grep -n "main" main.c'],
  ['echo','shell','Print arguments','echo hello'],
  ['printf','shell','Print formatted text','printf "%s\\n" hello'],
  ['true','shell','Return success','true'],
  ['false','shell','Return failure','false'],
  ['test','shell','Evaluate a condition','test -f notes.txt'],
  ['alias','shell','Create command aliases','alias ll="ls -la"'],
  ['unalias','shell','Remove an alias','unalias ll'],
  ['history','shell','Show command history','history'],
  ['help','shell','Show shell built-in help','help cd'],
  ['type','shell','Describe how a command is resolved','type cd'],
  ['command','shell','Run a command while bypassing aliases','command ls'],
  ['builtin','shell','Run a shell builtin explicitly','builtin cd /tmp'],
  ['source','shell','Read commands from a file','source env.sh'],
  ['read','shell','Read input into variables','read name'],
  ['set','shell','Set shell options and positional parameters','set -e'],
  ['unset','shell','Remove variables or functions','unset TEMP'],
  ['export','shell','Export an environment variable','export EDITOR=vi'],
  ['env','shell','Run a command with an environment','env VAR=value command'],
  ['printenv','shell','Print environment variables','printenv HOME'],
  ['getopts','shell','Parse shell script options','getopts "ab:" opt'],
  ['shift','shell','Shift positional parameters','shift'],
  ['wait','shell','Wait for background jobs','wait'],
  ['exec','shell','Replace the current shell process','exec sh'],
  ['eval','shell','Evaluate arguments as shell code','eval "echo $HOME"'],
  ['jobs','shell','List shell jobs','jobs'],
  ['fg','shell','Bring a job to the foreground','fg %1'],
  ['bg','shell','Resume a stopped job in background','bg %1'],
  ['disown','shell','Remove jobs from the shell job table','disown %1'],
  ['umask','permissions','Set or display the file creation mask','umask 022'],
  ['chmod','permissions','Change file permissions','chmod 755 script.sh'],
  ['chown','permissions','Change file ownership','chown user file'],
  ['chgrp','permissions','Change file group ownership','chgrp developers file'],
  ['getfacl','permissions','Read POSIX ACLs','getfacl file'],
  ['setfacl','permissions','Modify POSIX ACLs','setfacl -m u:alice:r file'],
  ['lsattr','permissions','Show filesystem attributes','lsattr file'],
  ['chattr','permissions','Change filesystem attributes','chattr +i file'],
  ['id','users','Show user and group IDs','id'],
  ['whoami','users','Print the current username','whoami'],
  ['groups','users','Show group membership','groups'],
  ['who','users','Show logged-in users','who'],
  ['w','users','Show users and their activity','w'],
  ['users','users','List logged-in usernames','users'],
  ['last','users','Show login history','last'],
  ['lastlog','users','Show last login information','lastlog'],
  ['getent','users','Query system databases','getent passwd root'],
  ['passwd','users','Change a user password','passwd'],
  ['ps','processes','List processes','ps aux'],
  ['top','processes','Monitor processes interactively','top'],
  ['htop','processes','Interactive process monitor','htop'],
  ['pgrep','processes','Find processes by name','pgrep ssh'],
  ['pkill','processes','Signal processes by name','pkill -TERM app'],
  ['kill','processes','Send a signal to a process','kill -TERM 1234'],
  ['killall','processes','Signal processes by name','killall app'],
  ['nice','processes','Run with a scheduling priority','nice -n 10 command'],
  ['renice','processes','Change process priority','renice 10 -p 1234'],
  ['nohup','processes','Run a command immune to hangups','nohup long-job &'],
  ['time','processes','Measure command execution time','time command'],
  ['strace','processes','Trace Linux system calls','strace -f ./app'],
  ['lsof','processes','List open files','lsof -p 1234'],
  ['pstree','processes','Display the process tree','pstree -p'],
  ['pidof','processes','Find process IDs by program name','pidof sh'],
  ['free','system','Display memory usage','free -h'],
  ['uname','system','Display kernel/system information','uname -a'],
  ['hostname','system','Show or set the host name','hostname'],
  ['uptime','system','Show system uptime and load','uptime'],
  ['dmesg','system','Read the kernel message buffer','dmesg | tail'],
  ['sysctl','system','Read or change kernel parameters','sysctl kernel.hostname'],
  ['lsb_release','system','Show distribution information','lsb_release -a'],
  ['arch','system','Print machine architecture','arch'],
  ['nproc','system','Print available processors','nproc'],
  ['lscpu','system','Display CPU information','lscpu'],
  ['lsmem','system','Display memory information','lsmem'],
  ['lsblk','storage','List block devices','lsblk'],
  ['blkid','storage','Print block device attributes','blkid'],
  ['df','storage','Show filesystem free space','df -h'],
  ['du','storage','Estimate file and directory usage','du -sh /root'],
  ['mount','storage','Show or mount filesystems','mount'],
  ['umount','storage','Unmount a filesystem','umount /mnt'],
  ['fdisk','storage','Partition disks interactively','fdisk -l'],
  ['parted','storage','Manage disk partitions','parted -l'],
  ['dd','storage','Copy and transform raw data','dd if=input.img of=output.img'],
  ['sync','storage','Flush filesystem buffers','sync'],
  ['fsck','storage','Check a filesystem','fsck /dev/sda1'],
  ['mkfs','storage','Create a filesystem','mkfs.ext4 /dev/sda1'],
  ['tar','archives','Create or extract tar archives','tar -czf backup.tar.gz project/'],
  ['gzip','archives','Compress with gzip','gzip notes.txt'],
  ['gunzip','archives','Decompress gzip data','gunzip notes.txt.gz'],
  ['bzip2','archives','Compress with bzip2','bzip2 data.txt'],
  ['bunzip2','archives','Decompress bzip2 data','bunzip2 data.txt.bz2'],
  ['xz','archives','Compress with xz','xz data.txt'],
  ['unxz','archives','Decompress xz data','unxz data.txt.xz'],
  ['zip','archives','Create ZIP archives','zip backup.zip notes.txt'],
  ['unzip','archives','Extract ZIP archives','unzip backup.zip'],
  ['zcat','archives','Read gzip-compressed text','zcat notes.txt.gz'],
  ['ar','archives','Create and manipulate archives','ar r lib.a object.o'],
  ['ip','network','Inspect and configure networking','ip addr'],
  ['ifconfig','network','Display legacy interface information','ifconfig'],
  ['ping','network','Test network reachability','ping -c 3 example.com'],
  ['ss','network','Inspect sockets','ss -tulpn'],
  ['netstat','network','Display network connections','netstat -tulpn'],
  ['route','network','Show the routing table','route -n'],
  ['arp','network','Inspect the ARP cache','arp -a'],
  ['dig','network','Query DNS','dig example.com'],
  ['nslookup','network','Query DNS interactively','nslookup example.com'],
  ['host','network','Perform a DNS lookup','host example.com'],
  ['curl','network','Transfer data over URLs','curl https://example.com'],
  ['wget','network','Download files over HTTP/HTTPS','wget https://example.com/file'],
  ['ssh','network','Connect to a remote shell','ssh user@host'],
  ['scp','network','Copy files over SSH','scp file user@host:/tmp/'],
  ['sftp','network','Transfer files over SSH','sftp user@host'],
  ['nc','network','Read and write network connections','nc -l 8080'],
  ['telnet','network','Connect to a TCP service','telnet host 80'],
  ['traceroute','network','Trace a network path','traceroute example.com'],
  ['mtr','network','Combine ping and traceroute diagnostics','mtr example.com'],
  ['git','development','Distributed version control','git status'],
  ['gcc','development','Compile C programs','gcc main.c -o app'],
  ['g++','development','Compile C++ programs','g++ main.cpp -o app'],
  ['make','development','Build projects from rules','make'],
  ['cmake','development','Generate build systems','cmake -S . -B build'],
  ['python3','development','Run Python 3','python3 script.py'],
  ['node','development','Run JavaScript with Node.js','node app.js'],
  ['javac','development','Compile Java source','javac Main.java'],
  ['java','development','Run a Java program','java Main'],
  ['go','development','Build or run Go programs','go run main.go'],
  ['rustc','development','Compile Rust source','rustc main.rs'],
  ['apk','packages','Manage Alpine Linux packages','apk search nginx'],
  ['apt','packages','Manage Debian-family packages','apt search nginx'],
  ['apt-get','packages','Low-level Debian package manager','apt-get update'],
  ['dnf','packages','Manage Fedora-family packages','dnf search nginx'],
  ['yum','packages','Legacy RPM package manager','yum install nginx'],
  ['pacman','packages','Manage Arch packages','pacman -Ss nginx'],
  ['rpm','packages','Query or manage RPM packages','rpm -qa'],
  ['dpkg','packages','Manage Debian packages','dpkg -l'],
  ['snap','packages','Manage snap packages','snap list'],
  ['flatpak','packages','Manage Flatpak applications','flatpak list'],
  ['systemctl','services','Control systemd services','systemctl status sshd'],
  ['service','services','Control traditional services','service sshd status'],
  ['journalctl','services','Read systemd journal logs','journalctl -n 50'],
  ['crontab','services','Manage scheduled cron jobs','crontab -l'],
  ['at','services','Schedule a one-time command','at 18:00'],
  ['logger','services','Write a message to the system log','logger "hello"'],
  ['openssl','security','Use OpenSSL cryptographic tools','openssl version'],
  ['sha256sum','security','Calculate SHA-256 checksums','sha256sum image.iso'],
  ['sha512sum','security','Calculate SHA-512 checksums','sha512sum file'],
  ['md5sum','security','Calculate MD5 checksums','md5sum file'],
  ['gpg','security','Use GNU Privacy Guard','gpg --version'],
  ['ssh-keygen','security','Create SSH keys','ssh-keygen -t ed25519'],
  ['sudo','security','Run a command with elevated privileges','sudo command'],
  ['su','security','Switch user identity','su - user'],
  ['chroot','advanced','Change the apparent root directory','chroot /srv/root /bin/sh'],
  ['nsenter','advanced','Enter Linux namespaces','nsenter -t 1234 -m -u -i -n -p'],
  ['unshare','advanced','Create new Linux namespaces','unshare -m /bin/sh'],
  ['mountpoint','advanced','Test whether a path is a mount point','mountpoint /proc'],
  ['envsubst','advanced','Substitute environment variables in text','envsubst < template.txt'],
  ['readelf','advanced','Inspect ELF binaries','readelf -h app'],
  ['objdump','advanced','Inspect object files','objdump -d app'],
  ['nm','advanced','List symbols from object files','nm app'],
  ['ldd','advanced','List shared library dependencies','ldd app'],
  ['ldconfig','advanced','Manage the shared library cache','ldconfig -p'],
  ['docker','containers','Manage Docker containers','docker ps'],
  ['podman','containers','Manage OCI containers','podman ps'],
  ['kubectl','containers','Control Kubernetes resources','kubectl get pods'],
  ['clear','shell','Clear the terminal display','clear'],
] as const satisfies readonly [string, CommandCategory, string, string][];

export const COMMAND_LESSONS: readonly LinuxCommandLesson[] = LINUX_COMMANDS.map(
  ([name, category, summary, example]) => ({ name, category, summary, example })
);

if (COMMAND_LESSONS.length !== 200) {
  throw new Error(`Linux command curriculum must contain exactly 200 entries; found ${COMMAND_LESSONS.length}`);
}

export function findCommand(name: string): LinuxCommandLesson | undefined {
  return COMMAND_LESSONS.find((command) => command.name === name);
}
