export type CommandCategory = 'navigation' | 'files' | 'text' | 'search' | 'shell' | 'permissions' | 'users' | 'processes' | 'system' | 'storage' | 'archives' | 'network' | 'development' | 'packages' | 'services' | 'security' | 'advanced' | 'containers';

export interface LinuxCommandLesson { name: string; category: CommandCategory; summary: string; example: string; }

/** Canonical 200-command learning index. Execution support is declared by the engine, not by this catalog. */
export const COMMAND_LESSONS: readonly LinuxCommandLesson[] = [
  { name: 'pwd', category: 'navigation', summary: 'Navigate the filesystem', example: 'pwd' },
  { name: 'ls', category: 'navigation', summary: 'Navigate the filesystem', example: 'ls' },
  { name: 'cd', category: 'navigation', summary: 'Navigate the filesystem', example: 'cd' },
  { name: 'tree', category: 'navigation', summary: 'Navigate the filesystem', example: 'tree' },
  { name: 'dirs', category: 'navigation', summary: 'Navigate the filesystem', example: 'dirs' },
  { name: 'pushd', category: 'navigation', summary: 'Navigate the filesystem', example: 'pushd' },
  { name: 'popd', category: 'navigation', summary: 'Navigate the filesystem', example: 'popd' },
  { name: 'realpath', category: 'navigation', summary: 'Navigate the filesystem', example: 'realpath' },
  { name: 'basename', category: 'navigation', summary: 'Navigate the filesystem', example: 'basename' },
  { name: 'dirname', category: 'navigation', summary: 'Navigate the filesystem', example: 'dirname' },
  { name: 'touch', category: 'files', summary: 'Create, inspect, copy, move, link, or remove files', example: 'touch' },
  { name: 'cat', category: 'files', summary: 'Create, inspect, copy, move, link, or remove files', example: 'cat' },
  { name: 'cp', category: 'files', summary: 'Create, inspect, copy, move, link, or remove files', example: 'cp' },
  { name: 'mv', category: 'files', summary: 'Create, inspect, copy, move, link, or remove files', example: 'mv' },
  { name: 'rm', category: 'files', summary: 'Create, inspect, copy, move, link, or remove files', example: 'rm' },
  { name: 'mkdir', category: 'files', summary: 'Create, inspect, copy, move, link, or remove files', example: 'mkdir' },
  { name: 'rmdir', category: 'files', summary: 'Create, inspect, copy, move, link, or remove files', example: 'rmdir' },
  { name: 'ln', category: 'files', summary: 'Create, inspect, copy, move, link, or remove files', example: 'ln' },
  { name: 'readlink', category: 'files', summary: 'Create, inspect, copy, move, link, or remove files', example: 'readlink' },
  { name: 'file', category: 'files', summary: 'Create, inspect, copy, move, link, or remove files', example: 'file' },
  { name: 'stat', category: 'files', summary: 'Create, inspect, copy, move, link, or remove files', example: 'stat' },
  { name: 'truncate', category: 'files', summary: 'Create, inspect, copy, move, link, or remove files', example: 'truncate' },
  { name: 'install', category: 'files', summary: 'Create, inspect, copy, move, link, or remove files', example: 'install' },
  { name: 'mktemp', category: 'files', summary: 'Create, inspect, copy, move, link, or remove files', example: 'mktemp' },
  { name: 'shred', category: 'files', summary: 'Create, inspect, copy, move, link, or remove files', example: 'shred' },
  { name: 'head', category: 'text', summary: 'Read and transform text', example: 'head' },
  { name: 'tail', category: 'text', summary: 'Read and transform text', example: 'tail' },
  { name: 'less', category: 'text', summary: 'Read and transform text', example: 'less' },
  { name: 'more', category: 'text', summary: 'Read and transform text', example: 'more' },
  { name: 'nl', category: 'text', summary: 'Read and transform text', example: 'nl' },
  { name: 'wc', category: 'text', summary: 'Read and transform text', example: 'wc' },
  { name: 'cut', category: 'text', summary: 'Read and transform text', example: 'cut' },
  { name: 'paste', category: 'text', summary: 'Read and transform text', example: 'paste' },
  { name: 'join', category: 'text', summary: 'Read and transform text', example: 'join' },
  { name: 'expand', category: 'text', summary: 'Read and transform text', example: 'expand' },
  { name: 'unexpand', category: 'text', summary: 'Read and transform text', example: 'unexpand' },
  { name: 'fold', category: 'text', summary: 'Read and transform text', example: 'fold' },
  { name: 'fmt', category: 'text', summary: 'Read and transform text', example: 'fmt' },
  { name: 'column', category: 'text', summary: 'Read and transform text', example: 'column' },
  { name: 'tr', category: 'text', summary: 'Read and transform text', example: 'tr' },
  { name: 'rev', category: 'text', summary: 'Read and transform text', example: 'rev' },
  { name: 'sort', category: 'text', summary: 'Read and transform text', example: 'sort' },
  { name: 'uniq', category: 'text', summary: 'Read and transform text', example: 'uniq' },
  { name: 'comm', category: 'text', summary: 'Read and transform text', example: 'comm' },
  { name: 'diff', category: 'text', summary: 'Read and transform text', example: 'diff' },
  { name: 'cmp', category: 'text', summary: 'Read and transform text', example: 'cmp' },
  { name: 'strings', category: 'text', summary: 'Read and transform text', example: 'strings' },
  { name: 'grep', category: 'search', summary: 'Search files, text, and commands', example: 'grep' },
  { name: 'egrep', category: 'search', summary: 'Search files, text, and commands', example: 'egrep' },
  { name: 'fgrep', category: 'search', summary: 'Search files, text, and commands', example: 'fgrep' },
  { name: 'find', category: 'search', summary: 'Search files, text, and commands', example: 'find' },
  { name: 'locate', category: 'search', summary: 'Search files, text, and commands', example: 'locate' },
  { name: 'which', category: 'search', summary: 'Search files, text, and commands', example: 'which' },
  { name: 'whereis', category: 'search', summary: 'Search files, text, and commands', example: 'whereis' },
  { name: 'xargs', category: 'search', summary: 'Search files, text, and commands', example: 'xargs' },
  { name: 'awk', category: 'search', summary: 'Search files, text, and commands', example: 'awk' },
  { name: 'sed', category: 'search', summary: 'Search files, text, and commands', example: 'sed' },
  { name: 'rg', category: 'search', summary: 'Search files, text, and commands', example: 'rg' },
  { name: 'echo', category: 'shell', summary: 'Use the shell and its built-ins', example: 'echo' },
  { name: 'printf', category: 'shell', summary: 'Use the shell and its built-ins', example: 'printf' },
  { name: 'true', category: 'shell', summary: 'Use the shell and its built-ins', example: 'true' },
  { name: 'false', category: 'shell', summary: 'Use the shell and its built-ins', example: 'false' },
  { name: 'test', category: 'shell', summary: 'Use the shell and its built-ins', example: 'test' },
  { name: 'alias', category: 'shell', summary: 'Use the shell and its built-ins', example: 'alias' },
  { name: 'unalias', category: 'shell', summary: 'Use the shell and its built-ins', example: 'unalias' },
  { name: 'history', category: 'shell', summary: 'Use the shell and its built-ins', example: 'history' },
  { name: 'help', category: 'shell', summary: 'Use the shell and its built-ins', example: 'help' },
  { name: 'type', category: 'shell', summary: 'Use the shell and its built-ins', example: 'type' },
  { name: 'command', category: 'shell', summary: 'Use the shell and its built-ins', example: 'command' },
  { name: 'builtin', category: 'shell', summary: 'Use the shell and its built-ins', example: 'builtin' },
  { name: 'source', category: 'shell', summary: 'Use the shell and its built-ins', example: 'source' },
  { name: 'read', category: 'shell', summary: 'Use the shell and its built-ins', example: 'read' },
  { name: 'set', category: 'shell', summary: 'Use the shell and its built-ins', example: 'set' },
  { name: 'unset', category: 'shell', summary: 'Use the shell and its built-ins', example: 'unset' },
  { name: 'export', category: 'shell', summary: 'Use the shell and its built-ins', example: 'export' },
  { name: 'env', category: 'shell', summary: 'Use the shell and its built-ins', example: 'env' },
  { name: 'printenv', category: 'shell', summary: 'Use the shell and its built-ins', example: 'printenv' },
  { name: 'getopts', category: 'shell', summary: 'Use the shell and its built-ins', example: 'getopts' },
  { name: 'shift', category: 'shell', summary: 'Use the shell and its built-ins', example: 'shift' },
  { name: 'wait', category: 'shell', summary: 'Use the shell and its built-ins', example: 'wait' },
  { name: 'exec', category: 'shell', summary: 'Use the shell and its built-ins', example: 'exec' },
  { name: 'eval', category: 'shell', summary: 'Use the shell and its built-ins', example: 'eval' },
  { name: 'jobs', category: 'shell', summary: 'Use the shell and its built-ins', example: 'jobs' },
  { name: 'fg', category: 'shell', summary: 'Use the shell and its built-ins', example: 'fg' },
  { name: 'bg', category: 'shell', summary: 'Use the shell and its built-ins', example: 'bg' },
  { name: 'disown', category: 'shell', summary: 'Use the shell and its built-ins', example: 'disown' },
  { name: 'umask', category: 'permissions', summary: 'Understand and change permissions', example: 'umask' },
  { name: 'chmod', category: 'permissions', summary: 'Understand and change permissions', example: 'chmod' },
  { name: 'chown', category: 'permissions', summary: 'Understand and change permissions', example: 'chown' },
  { name: 'chgrp', category: 'permissions', summary: 'Understand and change permissions', example: 'chgrp' },
  { name: 'getfacl', category: 'permissions', summary: 'Understand and change permissions', example: 'getfacl' },
  { name: 'setfacl', category: 'permissions', summary: 'Understand and change permissions', example: 'setfacl' },
  { name: 'lsattr', category: 'permissions', summary: 'Understand and change permissions', example: 'lsattr' },
  { name: 'chattr', category: 'permissions', summary: 'Understand and change permissions', example: 'chattr' },
  { name: 'id', category: 'users', summary: 'Inspect users and groups', example: 'id' },
  { name: 'whoami', category: 'users', summary: 'Inspect users and groups', example: 'whoami' },
  { name: 'groups', category: 'users', summary: 'Inspect users and groups', example: 'groups' },
  { name: 'who', category: 'users', summary: 'Inspect users and groups', example: 'who' },
  { name: 'w', category: 'users', summary: 'Inspect users and groups', example: 'w' },
  { name: 'users', category: 'users', summary: 'Inspect users and groups', example: 'users' },
  { name: 'last', category: 'users', summary: 'Inspect users and groups', example: 'last' },
  { name: 'lastlog', category: 'users', summary: 'Inspect users and groups', example: 'lastlog' },
  { name: 'getent', category: 'users', summary: 'Inspect users and groups', example: 'getent' },
  { name: 'passwd', category: 'users', summary: 'Inspect users and groups', example: 'passwd' },
  { name: 'ps', category: 'processes', summary: 'Inspect and control processes', example: 'ps' },
  { name: 'top', category: 'processes', summary: 'Inspect and control processes', example: 'top' },
  { name: 'htop', category: 'processes', summary: 'Inspect and control processes', example: 'htop' },
  { name: 'pgrep', category: 'processes', summary: 'Inspect and control processes', example: 'pgrep' },
  { name: 'pkill', category: 'processes', summary: 'Inspect and control processes', example: 'pkill' },
  { name: 'kill', category: 'processes', summary: 'Inspect and control processes', example: 'kill' },
  { name: 'killall', category: 'processes', summary: 'Inspect and control processes', example: 'killall' },
  { name: 'nice', category: 'processes', summary: 'Inspect and control processes', example: 'nice' },
  { name: 'renice', category: 'processes', summary: 'Inspect and control processes', example: 'renice' },
  { name: 'nohup', category: 'processes', summary: 'Inspect and control processes', example: 'nohup' },
  { name: 'time', category: 'processes', summary: 'Inspect and control processes', example: 'time' },
  { name: 'strace', category: 'processes', summary: 'Inspect and control processes', example: 'strace' },
  { name: 'lsof', category: 'processes', summary: 'Inspect and control processes', example: 'lsof' },
  { name: 'pstree', category: 'processes', summary: 'Inspect and control processes', example: 'pstree' },
  { name: 'pidof', category: 'processes', summary: 'Inspect and control processes', example: 'pidof' },
  { name: 'free', category: 'system', summary: 'Inspect the running system', example: 'free' },
  { name: 'uname', category: 'system', summary: 'Inspect the running system', example: 'uname' },
  { name: 'hostname', category: 'system', summary: 'Inspect the running system', example: 'hostname' },
  { name: 'uptime', category: 'system', summary: 'Inspect the running system', example: 'uptime' },
  { name: 'dmesg', category: 'system', summary: 'Inspect the running system', example: 'dmesg' },
  { name: 'sysctl', category: 'system', summary: 'Inspect the running system', example: 'sysctl' },
  { name: 'lsb_release', category: 'system', summary: 'Inspect the running system', example: 'lsb_release' },
  { name: 'arch', category: 'system', summary: 'Inspect the running system', example: 'arch' },
  { name: 'nproc', category: 'system', summary: 'Inspect the running system', example: 'nproc' },
  { name: 'lscpu', category: 'system', summary: 'Inspect the running system', example: 'lscpu' },
  { name: 'lsmem', category: 'system', summary: 'Inspect the running system', example: 'lsmem' },
  { name: 'lsblk', category: 'storage', summary: 'Inspect disks and filesystems', example: 'lsblk' },
  { name: 'blkid', category: 'storage', summary: 'Inspect disks and filesystems', example: 'blkid' },
  { name: 'df', category: 'storage', summary: 'Inspect disks and filesystems', example: 'df' },
  { name: 'du', category: 'storage', summary: 'Inspect disks and filesystems', example: 'du' },
  { name: 'mount', category: 'storage', summary: 'Inspect disks and filesystems', example: 'mount' },
  { name: 'umount', category: 'storage', summary: 'Inspect disks and filesystems', example: 'umount' },
  { name: 'fdisk', category: 'storage', summary: 'Inspect disks and filesystems', example: 'fdisk' },
  { name: 'parted', category: 'storage', summary: 'Inspect disks and filesystems', example: 'parted' },
  { name: 'dd', category: 'storage', summary: 'Inspect disks and filesystems', example: 'dd' },
  { name: 'sync', category: 'storage', summary: 'Inspect disks and filesystems', example: 'sync' },
  { name: 'fsck', category: 'storage', summary: 'Inspect disks and filesystems', example: 'fsck' },
  { name: 'mkfs', category: 'storage', summary: 'Inspect disks and filesystems', example: 'mkfs' },
  { name: 'tar', category: 'archives', summary: 'Create and extract archives', example: 'tar' },
  { name: 'gzip', category: 'archives', summary: 'Create and extract archives', example: 'gzip' },
  { name: 'gunzip', category: 'archives', summary: 'Create and extract archives', example: 'gunzip' },
  { name: 'bzip2', category: 'archives', summary: 'Create and extract archives', example: 'bzip2' },
  { name: 'bunzip2', category: 'archives', summary: 'Create and extract archives', example: 'bunzip2' },
  { name: 'xz', category: 'archives', summary: 'Create and extract archives', example: 'xz' },
  { name: 'unxz', category: 'archives', summary: 'Create and extract archives', example: 'unxz' },
  { name: 'zip', category: 'archives', summary: 'Create and extract archives', example: 'zip' },
  { name: 'unzip', category: 'archives', summary: 'Create and extract archives', example: 'unzip' },
  { name: 'zcat', category: 'archives', summary: 'Create and extract archives', example: 'zcat' },
  { name: 'ar', category: 'archives', summary: 'Create and extract archives', example: 'ar' },
  { name: 'ip', category: 'network', summary: 'Inspect and test networking', example: 'ip' },
  { name: 'ifconfig', category: 'network', summary: 'Inspect and test networking', example: 'ifconfig' },
  { name: 'ping', category: 'network', summary: 'Inspect and test networking', example: 'ping' },
  { name: 'ss', category: 'network', summary: 'Inspect and test networking', example: 'ss' },
  { name: 'netstat', category: 'network', summary: 'Inspect and test networking', example: 'netstat' },
  { name: 'route', category: 'network', summary: 'Inspect and test networking', example: 'route' },
  { name: 'arp', category: 'network', summary: 'Inspect and test networking', example: 'arp' },
  { name: 'dig', category: 'network', summary: 'Inspect and test networking', example: 'dig' },
  { name: 'nslookup', category: 'network', summary: 'Inspect and test networking', example: 'nslookup' },
  { name: 'host', category: 'network', summary: 'Inspect and test networking', example: 'host' },
  { name: 'curl', category: 'network', summary: 'Inspect and test networking', example: 'curl' },
  { name: 'wget', category: 'network', summary: 'Inspect and test networking', example: 'wget' },
  { name: 'ssh', category: 'network', summary: 'Inspect and test networking', example: 'ssh' },
  { name: 'scp', category: 'network', summary: 'Inspect and test networking', example: 'scp' },
  { name: 'sftp', category: 'network', summary: 'Inspect and test networking', example: 'sftp' },
  { name: 'nc', category: 'network', summary: 'Inspect and test networking', example: 'nc' },
  { name: 'telnet', category: 'network', summary: 'Inspect and test networking', example: 'telnet' },
  { name: 'traceroute', category: 'network', summary: 'Inspect and test networking', example: 'traceroute' },
  { name: 'mtr', category: 'network', summary: 'Inspect and test networking', example: 'mtr' },
  { name: 'git', category: 'development', summary: 'Build and develop software', example: 'git' },
  { name: 'gcc', category: 'development', summary: 'Build and develop software', example: 'gcc' },
  { name: 'g++', category: 'development', summary: 'Build and develop software', example: 'g++' },
  { name: 'make', category: 'development', summary: 'Build and develop software', example: 'make' },
  { name: 'cmake', category: 'development', summary: 'Build and develop software', example: 'cmake' },
  { name: 'python3', category: 'development', summary: 'Build and develop software', example: 'python3' },
  { name: 'node', category: 'development', summary: 'Build and develop software', example: 'node' },
  { name: 'javac', category: 'development', summary: 'Build and develop software', example: 'javac' },
  { name: 'java', category: 'development', summary: 'Build and develop software', example: 'java' },
  { name: 'go', category: 'development', summary: 'Build and develop software', example: 'go' },
  { name: 'rustc', category: 'development', summary: 'Build and develop software', example: 'rustc' },
  { name: 'apk', category: 'packages', summary: 'Manage software packages', example: 'apk' },
  { name: 'apt', category: 'packages', summary: 'Manage software packages', example: 'apt' },
  { name: 'apt-get', category: 'packages', summary: 'Manage software packages', example: 'apt-get' },
  { name: 'dnf', category: 'packages', summary: 'Manage software packages', example: 'dnf' },
  { name: 'yum', category: 'packages', summary: 'Manage software packages', example: 'yum' },
  { name: 'pacman', category: 'packages', summary: 'Manage software packages', example: 'pacman' },
  { name: 'rpm', category: 'packages', summary: 'Manage software packages', example: 'rpm' },
  { name: 'dpkg', category: 'packages', summary: 'Manage software packages', example: 'dpkg' },
  { name: 'snap', category: 'packages', summary: 'Manage software packages', example: 'snap' },
  { name: 'flatpak', category: 'packages', summary: 'Manage software packages', example: 'flatpak' },
  { name: 'systemctl', category: 'services', summary: 'Inspect and manage services', example: 'systemctl' },
  { name: 'service', category: 'services', summary: 'Inspect and manage services', example: 'service' },
  { name: 'journalctl', category: 'services', summary: 'Inspect and manage services', example: 'journalctl' },
  { name: 'crontab', category: 'services', summary: 'Inspect and manage services', example: 'crontab' },
  { name: 'at', category: 'services', summary: 'Inspect and manage services', example: 'at' },
  { name: 'logger', category: 'services', summary: 'Inspect and manage services', example: 'logger' },
  { name: 'seq', category: 'shell', summary: 'Generate numeric sequences for shell practice', example: 'seq 1 5' },
];

if (COMMAND_LESSONS.length !== 200) throw new Error(`Expected 200 commands, found ${COMMAND_LESSONS.length}`);
export function findCommand(name: string): LinuxCommandLesson | undefined { return COMMAND_LESSONS.find((command) => command.name === name); }
