const VERSION='linux-foundations-1.0';const TOTAL=30;const PASS=80;const UPSTASH=Netlify.env.get('UPSTASH_REDIS_REST_URL');const TOKEN=Netlify.env.get('UPSTASH_REDIS_REST_TOKEN');const SECRET=Netlify.env.get('CERTIFICATE_SIGNING_SECRET');const ORIGIN=Netlify.env.get('TUTOR_ALLOWED_ORIGINS')||'https://linuxterminal.me';
type User={id?:unknown;email?:unknown;user_metadata?:{full_name?:unknown}};type Q={id:string;q:string;c:string[];a:string;t:string};
const BANK:Q[]=[
{id:'pwd',q:'Which command prints the current working directory?',c:['pwd','cd','ls','whoami'],a:'pwd',t:'navigation'},
{id:'ls',q:'Which ls form commonly shows hidden entries and long metadata?',c:['ls -la','ls -r','ls -p','ls -n'],a:'ls -la',t:'files'},
{id:'cd',q:'What does cd .. normally do?',c:['move to the parent directory','delete the parent','print the parent','copy the parent'],a:'move to the parent directory',t:'navigation'},
{id:'mkdir',q:'What does mkdir -p add?',c:['create missing parent directories','print permissions','remove parents','compress files'],a:'create missing parent directories',t:'files'},
{id:'touch',q:'What does touch normally do to an existing file?',c:['updates timestamps','deletes contents','changes owner','compresses it'],a:'updates timestamps',t:'files'},
{id:'cat',q:'What does cat file.txt normally write to stdout?',c:['the file contents','the file permissions only','the username','the file size only'],a:'the file contents',t:'files'},
{id:'cp',q:'Which command copies report.txt to backup.txt?',c:['cp report.txt backup.txt','mv report.txt backup.txt','ln report.txt backup.txt','cat report.txt backup.txt'],a:'cp report.txt backup.txt',t:'files'},
{id:'mv',q:'What is a common use of mv?',c:['move or rename paths','search text','show processes','change permissions'],a:'move or rename paths',t:'files'},
{id:'rm',q:'Which rm option is commonly needed for a directory tree?',c:['-r','-l','-n','-p'],a:'-r',t:'files'},
{id:'find',q:'Which find test restricts matches to regular files?',c:['-type f','-regular','-file','-kind file'],a:'-type f',t:'search'},
{id:'grep',q:'What does grep -n add to matching lines?',c:['line numbers','timestamps','permissions','network addresses'],a:'line numbers',t:'text'},
{id:'head',q:'What does head -n 5 request?',c:['the first five lines','the last five lines','five files','five words'],a:'the first five lines',t:'text'},
{id:'tail',q:'What does tail -n 20 request?',c:['the last twenty lines','the first twenty lines','twenty files','twenty words'],a:'the last twenty lines',t:'text'},
{id:'wc',q:'Which wc option counts lines?',c:['-l','-w','-c','-m'],a:'-l',t:'text'},
{id:'sort',q:'What does sort -n change?',c:['numeric comparison','duplicate removal','case conversion','line numbering'],a:'numeric comparison',t:'text'},
{id:'uniq',q:'Why is sort often used before uniq?',c:['uniq compares adjacent duplicates','uniq requires root','sort enables networking','uniq only reads binaries'],a:'uniq compares adjacent duplicates',t:'text'},
{id:'sed',q:'What does sed s/old/new/g represent?',c:['a text substitution','a permission change','a network request','a process search'],a:'a text substitution',t:'text'},
{id:'awk',q:'In awk, what does $1 normally mean?',c:['the first field','the first process','the first file','the first shell'],a:'the first field',t:'text'},
{id:'chmod',q:'What does chmod change?',c:['permission bits','file contents','ownership','kernel version'],a:'permission bits',t:'permissions'},
{id:'whoami',q:'What does whoami report?',c:['effective username','all users','hostname only','current directory'],a:'effective username',t:'users'},
{id:'ps',q:'What does ps normally provide?',c:['a process snapshot','a filesystem archive','a text editor','a network capture'],a:'a process snapshot',t:'processes'},
{id:'df',q:'Which command reports filesystem capacity?',c:['df','du','free','wc'],a:'df',t:'storage'},
{id:'du',q:'Which command estimates directory space usage?',c:['du','df','free','ps'],a:'du',t:'storage'},
{id:'free',q:'What does free report?',c:['memory and swap statistics','disk capacity','process IDs only','network routes'],a:'memory and swap statistics',t:'system'},
{id:'uname',q:'Which command displays kernel/system identification?',c:['uname','date','whoami','env'],a:'uname',t:'system'},
{id:'tar',q:'Which tar operation creates an archive?',c:['-c','-x','-t','-p'],a:'-c',t:'archives'},
{id:'gzip',q:'What is gzip primarily for?',c:['compression','encryption','filesystem repair','process scheduling'],a:'compression',t:'archives'},
{id:'curl',q:'What does curl -I commonly request for HTTP?',c:['response headers','a file listing','an SSH key','a filesystem mount'],a:'response headers',t:'network'},
{id:'ssh',q:'What does SSH provide for a remote shell?',c:['encrypted transport and authentication','compression only','a compiler','a local editor'],a:'encrypted transport and authentication',t:'network'},
{id:'gcc',q:'What does gcc -o app main.c name?',c:['the output executable','the source file','the compiler','the warning set'],a:'the output executable',t:'development'},
{id:'pipeline',q:'What does grep ERROR log | wc -l demonstrate?',c:['stdout piped into wc','stderr written to a file','two unrelated commands','a permission change'],a:'stdout piped into wc',t:'shell'},
{id:'redirect',q:'What does > normally do?',c:['redirect stdout and replace the destination','append stdout','redirect stderr only','create a pipeline'],a:'redirect stdout and replace the destination',t:'shell'},
{id:'status',q:'What does a non-zero exit status normally indicate?',c:['failure or a false condition','that output was printed','that the user is root','that cd ran'],a:'failure or a false condition',t:'shell'},
];
function shuffle<T>(a:readonly T[]):T[]{const x=[...a];for(let i=x.length-1;i>0;i--){const r=new Uint32Array(1);crypto.getRandomValues(r);const j=r[0]%(i+1);[x[i],x[j]]=[x[j],x[i]];}return x;}
const json=(b:Record<string,unknown>,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{'content-type':'application/json','cache-control':'no-store','access-control-allow-origin':ORIGIN,'vary':'Origin'}});
async function user(request:Request):Promise<User|null>{const a=request.headers.get('authorization'),c=request.headers.get('cookie');if(!a&&!c)return null;const h=new Headers();if(a?.match(/^Bearer\s+\S+$/i))h.set('authorization',a);else if(c)h.set('cookie',c);else return null;try{const r=await fetch(new URL('/.netlify/identity/user',request.url),{headers:h,cache:'no-store'});if(!r.ok)return null;const u=await r.json() as unknown;if(!u||typeof u!=='object')return null;const x=u as User;return typeof x.id==='string'&&x.id.trim()?x:null;}catch{return null;}}
async function redis(command:unknown[]){if(!UPSTASH||!TOKEN)throw new Error('Upstash persistence is not configured');const r=await fetch(UPSTASH,{method:'POST',headers:{authorization:`Bearer ${TOKEN}`,'content-type':'application/json'},body:JSON.stringify(command)});if(!r.ok)throw new Error('Upstash request failed');const v=await r.json() as {result?:unknown;error?:unknown};if(v.error)throw new Error(String(v.error));return v.result;}
async function sign(value:string){if(!SECRET)throw new Error('Certificate signing is not configured');const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value));return [...new Uint8Array(sig)].map(x=>x.toString(16).padStart(2,'0')).join('');}
const canonical=(r:{id:string;uid:string;name:string;score:number;total:number;pct:number;issued:string;version:string})=>[r.id,r.uid,r.name,r.score,r.total,r.pct,r.issued,r.version].join('|');
const safe=(x:string)=>x.replace(/[^a-zA-Z0-9:._-]/g,'_');
async function start(u:User){if(!UPSTASH||!TOKEN||!SECRET)return json({error:'Verified exam persistence/signing is not configured.'},503);const selected=shuffle(BANK).slice(0,TOTAL).map(q=>({id:q.id,q:q.q,c:shuffle(q.c),t:q.t}));const id=crypto.randomUUID();const stored={uid:String(u.id),version:VERSION,questions:selected.map(q=>{const full=BANK.find(x=>x.id===q.id)!;return {...q,a:full.a};}),started:new Date().toISOString()};await redis(['SET',`linuxterminal:exam:${id}`,JSON.stringify(stored),'EX',3600]);return json({attemptId:id,version:VERSION,total:TOTAL,passPercent:PASS,questions:selected.map(q=>({id:q.id,q:q.q,choices:q.c,topic:q.t}))});}
async function submit(u:User,body:unknown){if(!UPSTASH||!TOKEN||!SECRET)return json({error:'Verified exam persistence/signing is not configured.'},503);if(!body||typeof body!=='object')return json({error:'Invalid request body.'},400);const b=body as {attemptId?:unknown;answers?:unknown};if(typeof b.attemptId!=='string'||!Array.isArray(b.answers)||b.answers.length!==TOTAL)return json({error:`Exactly ${TOTAL} answers are required.`},400);const key=`linuxterminal:exam:${safe(b.attemptId)}`;const lock=await redis(['SET',`${key}:lock`,String(u.id),'EX',60,'NX']);if(lock!=='OK')return json({error:'This attempt is already being submitted.'},409);const raw=await redis(['GET',key]);if(typeof raw!=='string'){await redis(['DEL',`${key}:lock`]);return json({error:'Exam attempt expired or was not found.'},404);}const attempt=JSON.parse(raw) as {uid:string;version:string;questions:Array<{id:string;c:string[];a:string;t:string}>};if(attempt.uid!==String(u.id)||attempt.version!==VERSION){await redis(['DEL',`${key}:lock`]);return json({error:'Exam attempt does not belong to this account.'},403);}const answers=new Map<string,number>();for(const item of b.answers){if(!item||typeof item!=='object')return json({error:'Invalid answer.'},400);const x=item as {id?:unknown;choice?:unknown};if(typeof x.id!=='string'||!Number.isInteger(x.choice))return json({error:'Invalid answer.'},400);answers.set(x.id,x.choice as number);}if(answers.size!==TOTAL)return json({error:'Every question must be answered exactly once.'},400);let score=0;const topics:Record<string,{correct:number;total:number}>={};for(const q of attempt.questions){const choice=answers.get(q.id),correct=q.c.indexOf(q.a),ok=choice===correct;score+=ok?1:0;topics[q.t]??={correct:0,total:0};topics[q.t].total++;if(ok)topics[q.t].correct++;}const pct=Math.round(score/TOTAL*10000)/100;if(pct<PASS){await redis(['DEL',key,`${key}:lock`]);return json({passed:false,score,total:TOTAL,percentage:pct,version:VERSION,message:'Not passed. Review the tutorials and retake the free verified assessment.'});}const issued=new Date().toISOString(),name=(typeof u.user_metadata?.full_name==='string'&&u.user_metadata.full_name.trim()?u.user_metadata.full_name.trim():typeof u.email==='string'?u.email:'LinuxTerminal learner').slice(0,120),id=`LT-LNX-${new Date().getUTCFullYear()}-${crypto.randomUUID().replaceAll('-','').slice(0,10).toUpperCase()}`,unsigned={id,uid:String(u.id),name,score,total:TOTAL,pct,issued,version:VERSION},signature=await sign(canonical(unsigned));const certificate={...unsigned,signature};await redis(['SET',`linuxterminal:certificate:${id}`,JSON.stringify(certificate),'EX',157680000]);await redis(['DEL',key,`${key}:lock`]);return json({passed:true,certificate:{id,name,score,total:TOTAL,percentage:pct,issuedAt:issued,version:VERSION},topics,verificationPath:`/verify/?id=${encodeURIComponent(id)}`});}
async function verify(id:string){if(!id||id.length>80)return json({error:'Certificate ID is required.'},400);const raw=await redis(['GET',`linuxterminal:certificate:${safe(id)}`]);if(typeof raw!=='string')return json({error:'Certificate not found.'},404);const r=JSON.parse(raw) as {id:string;uid:string;name:string;score:number;total:number;pct:number;issued:string;version:string;signature:string};if(await sign(canonical(r))!==r.signature)return json({error:'Certificate signature verification failed.'},500);return json({certificate:{id:r.id,name:r.name,score:r.score,total:r.total,percentage:r.pct,passed:true,issuedAt:r.issued,version:r.version}});}
export default async(request:Request)=>{if(request.method==='OPTIONS')return new Response('',{status:204,headers:{'access-control-allow-origin':ORIGIN,'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization'}});try{const u=await user(request);const url=new URL(request.url),action=url.searchParams.get('action')||(request.method==='GET'?'verify':'');if(request.method==='GET'&&action==='verify')return verify(url.searchParams.get('id')||'');if(!u)return json({error:'Sign in to take the free verified exam.'},401);const body=request.method==='POST'?await request.json().catch(()=>({})):{};if(action==='start')return start(u);if(action==='submit')return submit(u,body);return json({error:'Unknown action.'},400);}catch(e){console.error('Certificate service failed',e instanceof Error?e.message:String(e));return json({error:'Certificate service unavailable.'},503);}};
export const config={path:'/api/certificate'};
