export type CommandIndexItem = { name: string; description: string; example: string };

export const COMMAND_INDEX: readonly CommandIndexItem[] = [
  { name: 'pwd', description: 'Navigate the filesystem', example: 'pwd' },
  { name: 'ls', description: 'Navigate the filesystem', example: 'ls -la' },
  { name: 'cd', description: 'Navigate the filesystem', example: 'cd /tmp' },
  { name: 'tree', description: 'Navigate the filesystem', example: 'tree' },
  { name: 'dirs', description: 'Navigate the filesystem', example: 'dirs' },
  { name: 'pushd', description: 'Navigate the filesystem', example: 'pushd' },
  { name: 'popd', description: 'Navigate the filesystem', example: 'popd' },
  { name: 'realpath', description: 'Navigate the filesystem', example: 'realpath' },
  { name: 'basename', description: 'Navigate the filesystem', example: 'basename' },
  { name: 'dirname', description: 'Navigate the filesystem', example: 'dirname' },
  { name: 'touch', description: 'Create and inspect files', example: 'touch notes.txt' },
  { name: 'cat', description: 'Create and inspect files', example: 'cat notes.txt' },
  { name: 'cp', description: 'Create and inspect files', example: 'cp' },
  { name: 'mv', description: 'Create and inspect files', example: 'mv' },
  { name: 'rm', description: 'Create and inspect files', example: 'rm' },
  { name: 'mkdir', description: 'Create and inspect files', example: 'mkdir practice' },
  { name: 'rmdir', description: 'Create and inspect files', example: 'rmdir' },
  { name: 'ln', description: 'Create and inspect files', example: 'ln' },
  { name: 'readlink', description: 'Create and inspect files', example: 'readlink' },
  { name: 'file', description: 'Create and inspect files', example: 'file' },
  { name: 'stat', description: 'Create and inspect files', example: 'stat' },
  { name: 'truncate', description: 'Create and inspect files', example: 'truncate' },
  { name: 'install', description: 'Create and inspect files', example: 'install' },
  { name: 'mktemp', description: 'Create and inspect files', example: 'mktemp' },
  { name: 'shred', description: 'Create and inspect files', example: 'shred' },
  { name: 'head', description: 'Read and transform text', example: 'head' },
  { name: 'tail', description: 'Read and transform text', example: 'tail' },
  { name: 'less', description: 'Read and transform text', example: 'less' },
  { name: 'more', description: 'Read and transform text', example: 'more' },
  { name: 'nl', description: 'Read and transform text', example: 'nl' },
  { name: 'wc', description: 'Read and transform text', example: 'wc' },
  { name: 'cut', description: 'Read and transform text', example: 'cut' },
  { name: 'paste', description: 'Read and transform text', example: 'paste' },
  { name: 'join', description: 'Read and transform text', example: 'join' },
  { name: 'expand', description: 'Read and transform text', example: 'expand' },
  { name: 'unexpand', description: 'Read and transform text', example: 'unexpand' },
  { name: 'fold', description: 'Read and transform text', example: 'fold' },
  { name: 'fmt', description: 'Read and transform text', example: 'fmt' },
  { name: 'column', description: 'Read and transform text', example: 'column' },
  { name: 'tr', description: 'Read and transform text', example: 'tr' },
  { name: 'rev', description: 'Read and transform text', example: 'rev' },
  { name: 'sort', description: 'Read and transform text', example: 'sort' },
  { name: 'uniq', description: 'Read and transform text', example: 'uniq' },
  { name: 'comm', description: 'Read and transform text', example: 'comm' },
  { name: 'diff', description: 'Read and transform text', example: 'diff' },
  { name: 'cmp', description: 'Read and transform text', example: 'cmp' },
  { name: 'strings', description: 'Read and transform text', example: 'strings' },
  { name: 'grep', description: 'Search files and text', example: 'grep -n Linux notes.txt' },
  { name: 'egrep', description: 'Search files and text', example: 'egrep' },
  { name: 'fgrep', description: 'Search files and text', example: 'fgrep' },
  { name: 'find', description: 'Search files and text', example: 'find . -name notes.txt' },
  { name: 'locate', description: 'Search files and text', example: 'locate' },
  { name: 'which', description: 'Search files and text', example: 'which' },
  { name: 'whereis', description: 'Search files and text', example: 'whereis' },
  { name: 'xargs', description: 'Search files and text', example: 'xargs' },
  { name: 'awk', description: 'Search files and text', example: 'awk' },
  { name: 'sed', description: 'Search files and text', example: 'sed' },
  { name: 'rg', description: 'Search files and text', example: 'rg' },
  { name: 'echo', description: 'Use the shell and its built-ins', example: "echo 'hello Linux'" },
  { name: 'printf', description: 'Use the shell and its built-ins', example: "printf '%s\\n' Linux" },
  { name: 'true', description: 'Use the shell and its built-ins', example: 'true' },
  { name: 'false', description: 'Use the shell and its built-ins', example: 'false' },
  { name: 'test', description: 'Use the shell and its built-ins', example: 'test' },
  { name: 'alias', description: 'Use the shell and its built-ins', example: 'alias' },
  { name: 'unalias', description: 'Use the shell and its built-ins', example: 'unalias' },
  { name: 'history', description: 'Use the shell and its built-ins', example: 'history' },
  { name: 'help', description: 'Use the shell and its built-ins', example: 'help' },
  { name: 'type', description: 'Use the shell and its built-ins', example: 'type' },
  { name: 'command', description: 'Use the shell and its built-ins', example: 'command' },
  { name: 'builtin', description: 'Use the shell and its built-ins', example: 'builtin' },
  { name: 'source', description: 'Use the shell and its built-ins', example: 'source' },
  { name: 'read', description: 'Use the shell and its built-ins', example: 'read' },
  { name: 'set', description: 'Use the shell and its built-ins', example: 'set' },
  { name: 'unset', description: 'Use the shell and its built-ins', example: 'unset' },
  { name: 'export', description: 'Use the shell and its built-ins', example: 'export' },
  { name: 'env', description: 'Use the shell and its built-ins', example: 'env' },
  { name: 'printenv', description: 'Use the shell and its built-ins', example: 'printenv' },
  { name: 'getopts', description: 'Use the shell and its built-ins', example: 'getopts' },
  { name: 'shift', description: 'Use the shell and its built-ins', example: 'shift' },
  { name: 'wait', description: 'Use the shell and its built-ins', example: 'wait' },
  { name: 'exec', description: 'Use the shell and its built-ins', example: 'exec' },
  { name: 'eval', description: 'Use the shell and its built-ins', example: 'eval' },
  { name: 'jobs', description: 'Use the shell and its built-ins', example: 'jobs' },
  { name: 'fg', description: 'Use the shell and its built-ins', example: 'fg' },
  { name: 'bg', description: 'Use the shell and its built-ins', example: 'bg' },
  { name: 'disown', description: 'Use the shell and its built-ins', example: 'disown' },
  { name: 'umask', description: 'Understand and change permissions', example: 'umask' },
  { name: 'chmod', description: 'Understand and change permissions', example: 'chmod' },
  { name: 'chown', description: 'Understand and change permissions', example: 'chown' },
  { name: 'chgrp', description: 'Understand and change permissions', example: 'chgrp' },
  { name: 'getfacl', description: 'Understand and change permissions', example: 'getfacl' },
  { name: 'setfacl', description: 'Understand and change permissions', example: 'setfacl' },
  { name: 'lsattr', description: 'Understand and change permissions', example: 'lsattr' },
  { name: 'chattr', description: 'Understand and change permissions', example: 'chattr' },
  { name: 'id', description: 'Inspect users and groups', example: 'id' },
  { name: 'whoami', description: 'Inspect users and groups', example: 'whoami' },
  { name: 'groups', description: 'Inspect users and groups', example: 'groups' },
  { name: 'who', description: 'Inspect users and groups', example: 'who' },
  { name: 'w', description: 'Inspect users and groups', example: 'w' },
  { name: 'users', description: 'Inspect users and groups', example: 'users' },
  { name: 'last', description: 'Inspect users and groups', example: 'last' },
  { name: 'lastlog', description: 'Inspect users and groups', example: 'lastlog' },
  { name: 'getent', description: 'Inspect users and groups', example: 'getent' },
  { name: 'passwd', description: 'Inspect users and groups', example: 'passwd' },
  { name: 'ps', description: 'Inspect and control processes', example: 'ps aux' },
  { name: 'top', description: 'Inspect and control processes', example: 'top' },
  { name: 'htop', description: 'Inspect and control processes', example: 'htop' },
  { name: 'pgrep', description: 'Inspect and control processes', example: 'pgrep' },
  { name: 'pkill', description: 'Inspect and control processes', example: 'pkill' },
  { name: 'kill', description: 'Inspect and control processes', example: 'kill' },
  { name: 'killall', description: 'Inspect and control processes', example: 'killall' },
  { name: 'nice', description: 'Inspect and control processes', example: 'nice' },
  { name: 'renice', description: 'Inspect and control processes', example: 'renice' },
  { name: 'nohup', description: 'Inspect and control processes', example: 'nohup' },
  { name: 'time', description: 'Inspect and control processes', example: 'time' },
  { name: 'strace', description: 'Inspect and control processes', example: 'strace' },
  { name: 'lsof', description: 'Inspect and control processes', example: 'lsof' },
  { name: 'pstree', description: 'Inspect and control processes', example: 'pstree' },
  { name: 'pidof', description: 'Inspect and control processes', example: 'pidof' },
  { name: 'free', description: 'Inspect the running system', example: 'free -h' },
  { name: 'uname', description: 'Inspect the running system', example: 'uname -a' },
  { name: 'hostname', description: 'Inspect the running system', example: 'hostname' },
  { name: 'uptime', description: 'Inspect the running system', example: 'uptime' },
  { name: 'dmesg', description: 'Inspect the running system', example: 'dmesg' },
  { name: 'sysctl', description: 'Inspect the running system', example: 'sysctl' },
  { name: 'lsb_release', description: 'Inspect the running system', example: 'lsb_release' },
  { name: 'arch', description: 'Inspect the running system', example: 'arch' },
  { name: 'nproc', description: 'Inspect the running system', example: 'nproc' },
  { name: 'lscpu', description: 'Inspect the running system', example: 'lscpu' },
  { name: 'lsmem', description: 'Inspect the running system', example: 'lsmem' },
  { name: 'lsblk', description: 'Inspect disks and filesystems', example: 'lsblk' },
  { name: 'blkid', description: 'Inspect disks and filesystems', example: 'blkid' },
  { name: 'df', description: 'Inspect disks and filesystems', example: 'df -h' },
  { name: 'du', description: 'Inspect disks and filesystems', example: 'du -sh .' },
  { name: 'mount', description: 'Inspect disks and filesystems', example: 'mount' },
  { name: 'umount', description: 'Inspect disks and filesystems', example: 'umount' },
  { name: 'fdisk', description: 'Inspect disks and filesystems', example: 'fdisk' },
  { name: 'parted', description: 'Inspect disks and filesystems', example: 'parted' },
  { name: 'dd', description: 'Inspect disks and filesystems', example: 'dd' },
  { name: 'sync', description: 'Inspect disks and filesystems', example: 'sync' },
  { name: 'fsck', description: 'Inspect disks and filesystems', example: 'fsck' },
  { name: 'mkfs', description: 'Inspect disks and filesystems', example: 'mkfs' },
  { name: 'tar', description: 'Create and extract archives', example: 'tar --help' },
  { name: 'gzip', description: 'Create and extract archives', example: 'gzip' },
  { name: 'gunzip', description: 'Create and extract archives', example: 'gunzip' },
  { name: 'bzip2', description: 'Create and extract archives', example: 'bzip2' },
  { name: 'bunzip2', description: 'Create and extract archives', example: 'bunzip2' },
  { name: 'xz', description: 'Create and extract archives', example: 'xz' },
  { name: 'unxz', description: 'Create and extract archives', example: 'unxz' },
  { name: 'zip', description: 'Create and extract archives', example: 'zip' },
  { name: 'unzip', description: 'Create and extract archives', example: 'unzip' },
  { name: 'zcat', description: 'Create and extract archives', example: 'zcat' },
  { name: 'ar', description: 'Create and extract archives', example: 'ar' },
  { name: 'ip', description: 'Inspect and test networking', example: 'ip addr' },
  { name: 'ifconfig', description: 'Inspect and test networking', example: 'ifconfig' },
  { name: 'ping', description: 'Inspect and test networking', example: 'ping -c 4 example.invalid' },
  { name: 'ss', description: 'Inspect and test networking', example: 'ss' },
  { name: 'netstat', description: 'Inspect and test networking', example: 'netstat' },
  { name: 'route', description: 'Inspect and test networking', example: 'route' },
  { name: 'arp', description: 'Inspect and test networking', example: 'arp' },
  { name: 'dig', description: 'Inspect and test networking', example: 'dig' },
  { name: 'nslookup', description: 'Inspect and test networking', example: 'nslookup' },
  { name: 'host', description: 'Inspect and test networking', example: 'host' },
  { name: 'curl', description: 'Inspect and test networking', example: 'curl https://example.com' },
  { name: 'wget', description: 'Inspect and test networking', example: 'wget' },
  { name: 'ssh', description: 'Inspect and test networking', example: 'ssh --help' },
  { name: 'scp', description: 'Inspect and test networking', example: 'scp' },
  { name: 'sftp', description: 'Inspect and test networking', example: 'sftp' },
  { name: 'nc', description: 'Inspect and test networking', example: 'nc' },
  { name: 'telnet', description: 'Inspect and test networking', example: 'telnet' },
  { name: 'traceroute', description: 'Inspect and test networking', example: 'traceroute' },
  { name: 'mtr', description: 'Inspect and test networking', example: 'mtr' },
  { name: 'git', description: 'Build and develop software', example: 'git --version' },
  { name: 'gcc', description: 'Build and develop software', example: 'gcc --version' },
  { name: 'g++', description: 'Build and develop software', example: 'g++' },
  { name: 'make', description: 'Build and develop software', example: 'make --version' },
  { name: 'cmake', description: 'Build and develop software', example: 'cmake' },
  { name: 'python3', description: 'Build and develop software', example: 'python3 --version' },
  { name: 'node', description: 'Build and develop software', example: 'node --version' },
  { name: 'javac', description: 'Build and develop software', example: 'javac' },
  { name: 'java', description: 'Build and develop software', example: 'java --version' },
  { name: 'go', description: 'Build and develop software', example: 'go' },
  { name: 'rustc', description: 'Build and develop software', example: 'rustc' },
  { name: 'apk', description: 'Manage software packages', example: 'apk' },
  { name: 'apt', description: 'Manage software packages', example: 'apt' },
  { name: 'apt-get', description: 'Manage software packages', example: 'apt-get' },
  { name: 'dnf', description: 'Manage software packages', example: 'dnf' },
  { name: 'yum', description: 'Manage software packages', example: 'yum' },
  { name: 'pacman', description: 'Manage software packages', example: 'pacman' },
  { name: 'rpm', description: 'Manage software packages', example: 'rpm' },
  { name: 'dpkg', description: 'Manage software packages', example: 'dpkg' },
  { name: 'snap', description: 'Manage software packages', example: 'snap' },
  { name: 'flatpak', description: 'Manage software packages', example: 'flatpak' },
  { name: 'systemctl', description: 'Inspect and manage services', example: 'systemctl' },
  { name: 'service', description: 'Inspect and manage services', example: 'service' },
  { name: 'journalctl', description: 'Inspect and manage services', example: 'journalctl' },
  { name: 'crontab', description: 'Inspect and manage services', example: 'crontab' },
  { name: 'at', description: 'Inspect and manage services', example: 'at' },
  { name: 'logger', description: 'Inspect and manage services', example: 'logger' },
  { name: 'seq', description: 'Generate numeric sequences for shell practice', example: 'seq 1 5' },
];

if (COMMAND_INDEX.length !== 200) throw new Error(`Expected 200 command entries, found ${COMMAND_INDEX.length}`);

export default async (_request: Request) => {
  return new Response(JSON.stringify(COMMAND_INDEX), {
    status: 200,
    headers: {
      'content-type': 'application/json; charset=UTF-8',
      'cache-control': 'public,max-age=300',
    },
  });
};

export const config = { path: '/command-data' };
