import { COMMAND_INDEX } from './command-data.ts';

const esc = (value: string) => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');
const byName = new Map(COMMAND_INDEX.map(item => [item.name, item]));
const shellDemo = (name: string, example: string) => `<svg viewBox="0 0 900 280" role="img" aria-label="LinuxTerminal.me terminal demo for ${esc(name)}" xmlns="http://www.w3.org/2000/svg"><rect width="900" height="280" rx="18" fill="#06111f"/><rect width="900" height="42" rx="18" fill="#102845"/><circle cx="24" cy="21" r="7" fill="#ff5f56"/><circle cx="48" cy="21" r="7" fill="#ffbd2e"/><circle cx="72" cy="21" r="7" fill="#27c93f"/><text x="105" y="27" fill="#9eb2cf" font-family="monospace" font-size="16">linuxterminal.me • command demo</text><text x="28" y="92" fill="#45e09a" font-family="monospace" font-size="18">$ ${esc(example)}</text><text x="28" y="132" fill="#d9e8ff" font-family="monospace" font-size="16">Predict → run → inspect stdout/stderr → check exit status</text><text x="28" y="250" fill="#43d9ff" font-family="monospace" font-size="15">Safe learning reference • use Real Linux for genuine kernel behavior</text></svg>`;

function indexHtml() {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>200 Linux Commands — LinuxTerminal.me</title><meta name="description" content="The complete 200-command LinuxTerminal.me learning reference with categories, examples and safe browser practice."><meta name="robots" content="index,follow"><link rel="canonical" href="https://linuxterminal.me/commands/"><style>body{margin:0;background:#061426;color:#e8f1ff;font:16px/1.6 system-ui,sans-serif}main{max-width:1200px;margin:auto;padding:30px 20px 70px}a{color:#43d9ff}.nav{display:flex;gap:16px;flex-wrap:wrap;margin-bottom:24px}.hero{display:grid;grid-template-columns:2fr 1fr;gap:18px;align-items:end}.panel{background:#0c1e35;border:1px solid #24486e;border-radius:16px;padding:20px}.search{width:100%;box-sizing:border-box;padding:13px;background:#020914;border:1px solid #315b87;color:white;border-radius:10px}.toolbar{display:grid;grid-template-columns:1fr 190px;gap:12px;margin:20px 0}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.card h2{margin:8px 0}.pill{display:inline-block;color:#43d9ff;font:700 11px monospace;letter-spacing:.04em}.cta{display:inline-block;background:#1677ff;color:white;text-decoration:none;padding:8px 11px;border-radius:8px;font-weight:800}.muted{color:#9aacc4}@media(max-width:900px){.hero,.toolbar{grid-template-columns:1fr}.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:560px){.grid{grid-template-columns:1fr}}</style></head><body><main><nav class="nav"><a href="/">>_ LinuxTerminal.me</a><a href="/beginner/">Beginner</a><a href="/quiz/">500 Quiz</a><a href="/challenges/">100 Challenges</a><a href="/real-linux/">Real Linux</a></nav><section class="hero"><div><span class="pill">CANONICAL 200-COMMAND CURRICULUM</span><h1>Linux commands, explained and searchable.</h1><p class="muted">Every command in the LinuxTerminal.me curriculum appears here. Filter by name or category, open a lesson, then practice safely in the browser.</p></div><div class="panel"><strong>200 commands</strong><p class="muted">Navigation → files → text → shell → permissions → users → processes → system → storage → archives → network → development → packages → services.</p></div></section><section class="panel"><div class="toolbar"><input id="search" class="search" placeholder="Search pwd, grep, chmod, gcc…" aria-label="Search 200 Linux commands"><select id="category" class="search" aria-label="Filter commands"><option value="">All categories</option></select></div><div id="count" class="muted"></div><div id="list" class="grid" style="margin-top:14px"></div></section></main><script type="module" src="/commands-index.js"></script></body></html>`;
}

function lessonHtml(item: typeof COMMAND_INDEX[number]) {
  const url = `https://linuxterminal.me/commands/${item.name}/`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(item.name)} command — Linux tutorial | LinuxTerminal.me</title><meta name="description" content="${esc(item.description)}. Learn ${esc(item.name)} syntax, concepts, examples and safe Linux practice on LinuxTerminal.me."><meta name="robots" content="index,follow"><link rel="canonical" href="${url}"><style>body{margin:0;background:#061426;color:#e8f1ff;font:16px/1.6 system-ui,sans-serif}main{max-width:1000px;margin:auto;padding:28px 20px 70px}a{color:#43d9ff}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card{background:#0c1e35;border:1px solid #24486e;border-radius:16px;padding:20px}.demo{margin:18px 0;padding:8px;background:#020914;border:1px solid #315b87;border-radius:14px}.btn{display:inline-block;background:#1677ff;color:#fff;text-decoration:none;padding:11px 15px;border-radius:9px;font-weight:800}pre{background:#020914;padding:16px;border-radius:10px;overflow:auto}.muted{color:#9aacc4}@media(max-width:760px){.grid{grid-template-columns:1fr}}</style></head><body><main><nav><a href="/">>_ LinuxTerminal.me</a> · <a href="/commands/">All 200 commands</a> · <a href="/beginner/">Beginner</a> · <a href="/real-linux/">Real Linux</a></nav><h1><code>${esc(item.name)}</code></h1><p class="muted">${esc(item.description)}.</p><div class="demo">${shellDemo(item.name,item.example)}</div><section class="grid"><article class="card"><h2>What it teaches</h2><p>${esc(item.description)}. Exact options vary by distribution and implementation, so use the installed command's documentation for the full option set.</p></article><article class="card"><h2>Starter example</h2><pre>${esc(item.example)}</pre></article><article class="card"><h2>Practice</h2><p>Predict the result, run the command in the simulator, inspect stdout/stderr and check the exit status.</p><a class="btn" href="/beginner/?command=${encodeURIComponent(item.name)}">Open LinuxTerminal.me</a></article></section><section class="card" style="margin-top:16px"><h2>How it fits into Linux</h2><ol><li>The shell parses the command and arguments.</li><li>The command performs its operation and writes stdout/stderr.</li><li>The process returns an exit status used by scripts and conditionals.</li></ol><p>Need help? Use the contextual LinuxTerminal AI Tutor on the Beginner page.</p><a class="btn" href="/beginner/#tutor">Ask the AI Tutor</a></section></main></body></html>`;
}

export default async (request: Request) => {
  const pathname = new URL(request.url).pathname.replace(/\/+$/, '');
  const name = pathname.replace(/^\/commands\//, '');
  if (!name) return new Response(indexHtml(), { headers: { 'content-type': 'text/html; charset=UTF-8', 'cache-control': 'public,max-age=300' } });
  const item = byName.get(name);
  if (!item) return new Response('LinuxTerminal.me: command lesson not found.', { status: 404, headers: { 'content-type': 'text/plain; charset=utf-8' } });
  return new Response(lessonHtml(item), { headers: { 'content-type': 'text/html; charset=UTF-8', 'cache-control': 'public,max-age=300' } });
};

export const config = { path: '/commands/*' };
