export type CommandIndexItem = { name: string; description: string; example: string };

export const COMMAND_INDEX: readonly CommandIndexItem[] = [
  { name: 'pwd', description: 'Navigate the filesystem', example: 'pwd' },
  { name: 'ls', description: 'Navigate the filesystem', example: 'ls -la' },
  { name: 'cd', description: 'Navigate the filesystem', example: 'cd /tmp' },
  { name: 'tree', description: 'Navigate the filesystem', example: 'tree .' },
  { name: 'dirs', description: 'Navigate the filesystem', example: 'dirs -v' },
  { name: 'pushd', description: 'Navigate the filesystem', example: 'pushd /tmp' },
  { name: 'popd', description: 'Navigate the filesystem', example: 'pushd /tmp && popd' },
  { name: 'realpath', description: 'Navigate the filesystem', example: 'realpath notes.txt' },
  { name: 'basename', description: 'Navigate the filesystem', example: 'basename notes.txt' },
  { name: 'dirname', description: 'Navigate the filesystem', example: 'dirname notes.txt' },
  { name: 'touch', description: 'Create and inspect files', example: 'touch notes.txt' },
  { name: 'cat', description: 'Create and inspect files', example: 'cat notes.txt' },
  { name: 'cp', description: 'Create and inspect files', example: 'cp notes.txt backup.txt' },
  { name: 'mv', description: 'Create and inspect files', example: 'mv notes.txt archive.txt' },
  { name: 'rm', description: 'Create and inspect files', example: 'rm old-notes.txt' },
  { name: 'mkdir', description: 'Create and inspect files', example: 'mkdir practice' },
  { name: 'rmdir', description: 'Create and inspect files', example: 'rmdir empty-dir' },
  { name: 'ln', description: 'Create and inspect files', example: 'ln notes.txt notes-copy.txt' },
  { name: 'readlink', description: 'Create and inspect files', example: 'readlink notes-link' },
  { name: 'file', description: 'Create and inspect files', example: 'file notes.txt' },
  { name: 'stat', description: 'Create and inspect files', example: 'stat notes.txt' },
  { name: 'truncate', description: 'Create and inspect files', example: 'truncate -s 0 scratch.txt' },
  { name: 'install', description: 'Create and inspect files', example: 'install --help' },
  { name: 'mktemp', description: 'Create and inspect files', example: 'mktemp /tmp/linuxlab.XXXXXX' },
  { name: 'shred', description: 'Create and inspect files', example: 'shred --help' },
  { name: 'head', description: 'Read and transform text', example: 'head -n 10 notes.txt' },
  { name: 'tail', description: 'Read and transform text', example: 'tail -n 10 notes.txt' },
  { name: 'less', description: 'Read and transform text', example: 'less notes.txt' },
  { name: 'more', description: 'Read and transform text', example: 'more notes.txt' },
  { name: 'nl', description: 'Read and transform text', example: 'nl -ba notes.txt' },
  { name: 'wc', description: 'Read and transform text', example: 'wc -l notes.txt' },
  { name: 'cut', description: 'Read and transform text', example: 'cut -d, -f1 data.csv' },
  { name: 'paste', description: 'Read and transform text', example: 'paste names.txt scores.txt' },
  { name: 'join', description: 'Read and transform text', example: 'join names.txt scores.txt' },
  { name: 'expand', description: 'Read and transform text', example: 'expand notes.txt' },
  { name: 'unexpand', description: 'Read and transform text', example: 'unexpand notes.txt' },
  { name: 'fold', description: 'Read and transform text', example: 'fold -w 40 notes.txt' },
  { name: 'fmt', description: 'Read and transform text', example: 'fmt -w 72 notes.txt' },
  { name: 'column', description: 'Read and transform text', example: 'column -t data.txt' },
  { name: 'tr', description: 'Read and transform text', example: "tr '[:lower:]' '[:upper:]' < notes.txt" },
  { name: 'rev', description: 'Read and transform text', example: 'rev notes.txt' },
  { name: 'sort', description: 'Read and transform text', example: 'sort notes.txt' },
  { name: 'uniq', description: 'Read and transform text', example: 'uniq names.txt' },
  { name: 'comm', description: 'Read and transform text', example: 'comm names-a.txt names-b.txt' },
  { name: 'diff', description: 'Read and transform text', example: 'diff old.txt new.txt' },
  { name: 'cmp', description: 'Read and transform text', example: 'cmp old.txt new.txt' },
  { name: 'strings', description: 'Read and transform text', example: 'strings app.bin' },
  { name: 'grep', description: 'Search files and text', example: 'grep -n Linux notes.txt' },
  { name: 'egrep', description: 'Search files and text', example: "egrep -n 'Linux|Unix' notes.txt" },
  { name: 'fgrep', description: 'Search files and text', example: 'fgrep -n Linux notes.txt' },
  { name: 'find', description: 'Search files and text', example: 'find . -name notes.txt' },
  { name: 'locate', description: 'Search files and text', example: 'locate notes.txt' },
  { name: 'which', description: 'Search files and text', example: 'which python3' },
  { name: 'whereis', description: 'Search files and text', example: 'whereis python3' },
  { name: 'xargs', description: 'Search files and text', example: "printf '%s\\n' notes.txt | xargs -n1 basename" },
  { name: 'awk', description: 'Search files and text', example: "awk '{print $1}' notes.txt" },
  { name: 'sed', description: 'Search files and text', example: "sed -n '1,5p' notes.txt" },
  { name: 'rg', description: 'Search files and text', example: 'rg -n Linux notes.txt' },
  { name: 'echo', description: 'Use the shell and its built-ins', example: "echo 'hello Linux'" },
  { name: 'printf', description: 'Use the shell and its built-ins', example: "printf '%s\\n' Linux" },
  { name: 'true', description: 'Use the shell and its built-ins', example: 'help true' },
  { name: 'false', description: 'Use the shell and its built-ins', example: 'help false' },
  { name: 'test', description: 'Use the shell and its built-ins', example: 'test -f notes.txt' },
  { name: 'alias', description: 'Use the shell and its built-ins', example: "alias ll='ls -la'" },
  { name: 'unalias', description: 'Use the shell and its built-ins', example: 'unalias ll' },
  { name: 'history', description: 'Use the shell and its built-ins', example: 'history 10' },
  { name: 'help', description: 'Use the shell and its built-ins', example: 'help cd' },
  { name: 'type', description: 'Use the shell and its built-ins', example: 'type cd' },
  { name: 'command', description: 'Use the shell and its built-ins', example: 'command -v python3' },
  { name: 'builtin', description: 'Use the shell and its built-ins', example: 'help builtin' },
  { name: 'source', description: 'Use the shell and its built-ins', example: 'help source' },
  { name: 'read', description: 'Use the shell and its built-ins', example: 'help read' },
  { name: 'set', description: 'Use the shell and its built-ins', example: 'set -o' },
  { name: 'unset', description: 'Use the shell and its built-ins', example: 'unset DEMO_VAR' },
  { name: 'export', description: 'Use the shell and its built-ins', example: 'export DEMO_VAR=linux' },
  { name: 'env', description: 'Use the shell and its built-ins', example: 'env | grep HOME' },
  { name: 'printenv', description: 'Use the shell and its built-ins', example: 'printenv HOME' },
  { name: 'getopts', description: 'Use the shell and its built-ins', example: 'help getopts' },
  { name: 'shift', description: 'Use the shell and its built-ins', example: 'help shift' },
  { name: 'wait', description: 'Use the shell and its built-ins', example: 'help wait' },
  { name: 'exec', description: 'Use the shell and its built-ins', example: 'help exec' },
  { name: 'eval', description: 'Use the shell and its built-ins', example: "eval 'printf %s\\n demo'" },
  { name: 'jobs', description: 'Use the shell and its built-ins', example: 'jobs -l' },
  { name: 'fg', description: 'Use the shell and its built-ins', example: 'help fg' },
  { name: 'bg', description: 'Use the shell and its built-ins', example: 'help bg' },
  { name: 'disown', description: 'Use the shell and its built-ins', example: 'help disown' },
  { name: 'umask', description: 'Understand and change permissions', example: 'umask -S' },
  { name: 'chmod', description: 'Understand and change permissions', example: 'chmod --help' },
  { name: 'chown', description: 'Understand and change permissions', example: 'chown --help' },
  { name: 'chgrp', description: 'Understand and change permissions', example: 'chgrp --help' },
  { name: 'getfacl', description: 'Understand and change permissions', example: 'getfacl notes.txt' },
  { name: 'setfacl', description: 'Understand and change permissions', example: 'setfacl --help' },
  { name: 'lsattr', description: 'Understand and change permissions', example: 'lsattr notes.txt' },
  { name: 'chattr', description: 'Understand and change permissions', example: 'chattr --help' },
  { name: 'id', description: 'Inspect users and groups', example: 'id -u' },
  { name: 'whoami', description: 'Inspect users and groups', example: 'whoami --help' },
  { name: 'groups', description: 'Inspect users and groups', example: 'groups $USER' },
  { name: 'who', description: 'Inspect users and groups', example: 'who -H' },
  { name: 'w', description: 'Inspect users and groups', example: 'w -h' },
  { name: 'users', description: 'Inspect users and groups', example: 'users' },
  { name: 'last', description: 'Inspect users and groups', example: 'last -n 5' },
  { name: 'lastlog', description: 'Inspect users and groups', example: 'lastlog | head' },
  { name: 'getent', description: 'Inspect users and groups', example: 'getent passwd $USER' },
  { name: 'passwd', description: 'Inspect users and groups', example: 'passwd --help' },
  { name: 'ps', description: 'Inspect and control processes', example: 'ps aux' },
  { name: 'top', description: 'Inspect and control processes', example: 'top -b -n 1' },
  { name: 'htop', description: 'Inspect and control processes', example: 'htop --help' },
  { name: 'pgrep', description: 'Inspect and control processes', example: 'pgrep -a ssh' },
  { name: 'pkill', description: 'Inspect and control processes', example: 'pkill --help' },
  { name: 'kill', description: 'Inspect and control processes', example: 'kill --help' },
  { name: 'killall', description: 'Inspect and control processes', example: 'killall --help' },
  { name: 'nice', description: 'Inspect and control processes', example: 'nice --help' },
  { name: 'renice', description: 'Inspect and control processes', example: 'renice --help' },
  { name: 'nohup', description: 'Inspect and control processes', example: 'nohup --help' },
  { name: 'time', description: 'Inspect and control processes', example: 'time echo Linux' },
  { name: 'strace', description: 'Inspect and control processes', example: 'strace --help' },
  { name: 'lsof', description: 'Inspect and control processes', example: 'lsof -p $$' },
  { name: 'pstree', description: 'Inspect and control processes', example: 'pstree -p $$' },
  { name: 'pidof', description: 'Inspect and control processes', example: 'pidof sh' },
  { name: 'free', description: 'Inspect the running system', example: 'free -h' },
  { name: 'uname', description: 'Inspect the running system', example: 'uname -a' },
  { name: 'hostname', description: 'Inspect the running system', example: 'hostname' },
  { name: 'uptime', description: 'Inspect the running system', example: 'uptime' },
  { name: 'dmesg', description: 'Inspect the running system', example: 'dmesg | tail -n 10' },
  { name: 'sysctl', description: 'Inspect the running system', example: 'sysctl -a | head' },
  { name: 'lsb_release', description: 'Inspect the running system', example: 'lsb_release -a' },
  { name: 'arch', description: 'Inspect the running system', example: 'arch' },
  { name: 'nproc', description: 'Inspect the running system', example: 'nproc' },
  { name: 'lscpu', description: 'Inspect the running system', example: 'lscpu | head' },
  { name: 'lsmem', description: 'Inspect the running system', example: 'lsmem | head' },
  { name: 'lsblk', description: 'Inspect disks and filesystems', example: 'lsblk -f' },
  { name: 'blkid', description: 'Inspect disks and filesystems', example: 'blkid --help' },
  { name: 'df', description: 'Inspect disks and filesystems', example: 'df -h' },
  { name: 'du', description: 'Inspect disks and filesystems', example: 'du -sh .' },
  { name: 'mount', description: 'Inspect disks and filesystems', example: 'mount --help' },
  { name: 'umount', description: 'Inspect disks and filesystems', example: 'umount --help' },
  { name: 'fdisk', description: 'Inspect disks and filesystems', example: 'fdisk --help' },
  { name: 'parted', description: 'Inspect disks and filesystems', example: 'parted --help' },
  { name: 'dd', description: 'Inspect disks and filesystems', example: 'dd --help' },
  { name: 'sync', description: 'Inspect disks and filesystems', example: 'sync --help' },
  { name: 'fsck', description: 'Inspect disks and filesystems', example: 'fsck --help' },
  { name: 'mkfs', description: 'Inspect disks and filesystems', example: 'mkfs --help' },
  { name: 'tar', description: 'Create and extract archives', example: 'tar --help' },
  { name: 'gzip', description: 'Create and extract archives', example: 'gzip --help' },
  { name: 'gunzip', description: 'Create and extract archives', example: 'gunzip --help' },
  { name: 'bzip2', description: 'Create and extract archives', example: 'bzip2 --help' },
  { name: 'bunzip2', description: 'Create and extract archives', example: 'bunzip2 --help' },
  { name: 'xz', description: 'Create and extract archives', example: 'xz --help' },
  { name: 'unxz', description: 'Create and extract archives', example: 'unxz --help' },
  { name: 'zip', description: 'Create and extract archives', example: 'zip --help' },
  { name: 'unzip', description: 'Create and extract archives', example: 'unzip --help' },
  { name: 'zcat', description: 'Create and extract archives', example: 'zcat notes.txt.gz' },
  { name: 'ar', description: 'Create and extract archives', example: 'ar --help' },
  { name: 'ip', description: 'Inspect and test networking', example: 'ip addr' },
  { name: 'ifconfig', description: 'Inspect and test networking', example: 'ifconfig' },
  { name: 'ping', description: 'Inspect and test networking', example: 'ping -c 4 example.invalid' },
  { name: 'ss', description: 'Inspect and test networking', example: 'ss -tuln' },
  { name: 'netstat', description: 'Inspect and test networking', example: 'netstat -tuln' },
  { name: 'route', description: 'Inspect and test networking', example: 'route -n' },
  { name: 'arp', description: 'Inspect and test networking', example: 'arp -n' },
  { name: 'dig', description: 'Inspect and test networking', example: 'dig example.com' },
  { name: 'nslookup', description: 'Inspect and test networking', example: 'nslookup example.com' },
  { name: 'host', description: 'Inspect and test networking', example: 'host example.com' },
  { name: 'curl', description: 'Inspect and test networking', example: 'curl https://example.com' },
  { name: 'wget', description: 'Inspect and test networking', example: 'wget --help' },
  { name: 'ssh', description: 'Inspect and test networking', example: 'ssh --help' },
  { name: 'scp', description: 'Inspect and test networking', example: 'scp --help' },
  { name: 'sftp', description: 'Inspect and test networking', example: 'sftp --help' },
  { name: 'nc', description: 'Inspect and test networking', example: 'nc --help' },
  { name: 'telnet', description: 'Inspect and test networking', example: 'telnet --help' },
  { name: 'traceroute', description: 'Inspect and test networking', example: 'traceroute --help' },
  { name: 'mtr', description: 'Inspect and test networking', example: 'mtr --help' },
  { name: 'git', description: 'Build and develop software', example: 'git --version' },
  { name: 'gcc', description: 'Build and develop software', example: 'gcc --version' },
  { name: 'g++', description: 'Build and develop software', example: 'g++ --version' },
  { name: 'make', description: 'Build and develop software', example: 'make --version' },
  { name: 'cmake', description: 'Build and develop software', example: 'cmake --version' },
  { name: 'python3', description: 'Build and develop software', example: 'python3 --version' },
  { name: 'node', description: 'Build and develop software', example: 'node --version' },
  { name: 'javac', description: 'Build and develop software', example: 'javac --version' },
  { name: 'java', description: 'Build and develop software', example: 'java --version' },
  { name: 'go', description: 'Build and develop software', example: 'go version' },
  { name: 'rustc', description: 'Build and develop software', example: 'rustc --version' },
  { name: 'apk', description: 'Manage software packages', example: 'apk --help' },
  { name: 'apt', description: 'Manage software packages', example: 'apt --help' },
  { name: 'apt-get', description: 'Manage software packages', example: 'apt-get --help' },
  { name: 'dnf', description: 'Manage software packages', example: 'dnf --help' },
  { name: 'yum', description: 'Manage software packages', example: 'yum --help' },
  { name: 'pacman', description: 'Manage software packages', example: 'pacman --help' },
  { name: 'rpm', description: 'Manage software packages', example: 'rpm --help' },
  { name: 'dpkg', description: 'Manage software packages', example: 'dpkg --help' },
  { name: 'snap', description: 'Manage software packages', example: 'snap --help' },
  { name: 'flatpak', description: 'Manage software packages', example: 'flatpak --help' },
  { name: 'systemctl', description: 'Inspect and manage services', example: 'systemctl --help' },
  { name: 'service', description: 'Inspect and manage services', example: 'service --help' },
  { name: 'journalctl', description: 'Inspect and manage services', example: 'journalctl --help' },
  { name: 'crontab', description: 'Inspect and manage services', example: 'crontab --help' },
  { name: 'at', description: 'Inspect and manage services', example: 'at --help' },
  { name: 'logger', description: 'Inspect and manage services', example: 'logger --help' },
  { name: 'seq', description: 'Generate numeric sequences for shell practice', example: 'seq 1 5' },
];

if (COMMAND_INDEX.length !== 200) throw new Error(`Expected 200 command entries, found ${COMMAND_INDEX.length}`);

export default async (_request: Request) => {
  return new Response(JSON.stringify(COMMAND_INDEX), {
    status: 200,
    headers: {
      'content-type': 'application/json; charset=UTF-8',
      'cache-control': 'public,max-age=300',
    },
  });
};

export const config = { path: '/command-data' };
