import { COMMAND_INDEX } from './command-data.ts';

const esc = (value: string) => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');
const byName = new Map(COMMAND_INDEX.map(item => [item.name, item]));
const categoryFor = (description: string) => description;

const shellDemo = (name: string, example: string) => `<svg viewBox="0 0 900 280" role="img" aria-label="LinuxTerminal.me terminal demo for ${esc(name)}" xmlns="http://www.w3.org/2000/svg"><rect width="900" height="280" rx="18" fill="#06111f"/><rect width="900" height="42" rx="18" fill="#102845"/><circle cx="24" cy="21" r="7" fill="#ff5f56"/><circle cx="48" cy="21" r="7" fill="#ffbd2e"/><circle cx="72" cy="21" r="7" fill="#27c93f"/><text x="105" y="27" fill="#9eb2cf" font-family="monospace" font-size="16">linuxterminal.me • command demo</text><text x="28" y="92" fill="#45e09a" font-family="monospace" font-size="18">$ ${esc(example)}</text><text x="28" y="132" fill="#d9e8ff" font-family="monospace" font-size="16">Predict → run → inspect stdout/stderr → check exit status</text><text x="28" y="250" fill="#43d9ff" font-family="monospace" font-size="15">Safe learning reference • use Real Linux for genuine kernel behavior</text></svg>`;

function commandCards() {
  return COMMAND_INDEX.map(item => `<article class="card command-card" data-name="${esc(item.name.toLowerCase())}" data-category="${esc(categoryFor(item.description).toLowerCase())}"><span class="pill">${esc(item.description)}</span><h2><code>${esc(item.name)}</code></h2><p class="muted">${esc(item.description)}.</p><pre>${esc(item.example)}</pre><a class="cta" href="/commands/${encodeURIComponent(item.name)}/">Open lesson</a></article>`).join('');
}

function indexHtml() {
  const categories = [...new Set(COMMAND_INDEX.map(item => item.description))].sort((a, b) => a.localeCompare(b));
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>200 Linux Commands — LinuxTerminal.me</title><meta name="description" content="The complete 200-command LinuxTerminal.me learning reference with categories, examples and safe browser practice."><meta name="robots" content="index,follow"><link rel="canonical" href="https://linuxterminal.me/commands/"><link rel="stylesheet" href="/commands.css"></head><body><main><nav class="nav"><a href="/">&gt;_ LinuxTerminal.me</a><a href="/beginner/">Beginner</a><a href="/quiz/">500 Quiz</a><a href="/challenges/">100 Challenges</a><a href="/real-linux/">Real Linux</a><a href="/login/">Sign in</a></nav><section class="hero"><div><span class="pill">CANONICAL 200-COMMAND CURRICULUM</span><h1>Linux commands, explained and searchable.</h1><p class="muted">Every command in the LinuxTerminal.me curriculum appears here. Filter by name or category, open a lesson, then practice safely in the browser.</p></div><div class="panel"><strong>200 commands</strong><p class="muted">Navigation → files → text → shell → permissions → users → processes → system → storage → archives → network → development → packages → services.</p></div></section><section class="panel"><div class="toolbar"><label class="sr-only" for="search">Search commands</label><input id="search" class="search" placeholder="Search pwd, grep, chmod, gcc…" aria-label="Search 200 Linux commands"><label class="sr-only" for="category">Filter category</label><select id="category" class="search" aria-label="Filter commands"><option value="">All categories</option>${categories.map(category => `<option value="${esc(category.toLowerCase())}">${esc(category)}</option>`).join('')}</select></div><div id="count" class="muted" aria-live="polite">${COMMAND_INDEX.length} commands</div><div id="list" class="grid">${commandCards()}</div></section></main><script type="module" src="/commands.js"></script></body></html>`;
}

function lessonHtml(item: typeof COMMAND_INDEX[number]) {
  const url = `https://linuxterminal.me/commands/${item.name}/`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(item.name)} command — Linux tutorial | LinuxTerminal.me</title><meta name="description" content="${esc(item.description)}. Learn ${esc(item.name)} syntax, concepts, examples and safe Linux practice on LinuxTerminal.me."><meta name="robots" content="index,follow"><link rel="canonical" href="${url}"><link rel="stylesheet" href="/commands.css"></head><body><main><nav><a href="/">&gt;_ LinuxTerminal.me</a> · <a href="/commands/">All 200 commands</a> · <a href="/beginner/">Beginner</a> · <a href="/real-linux/">Real Linux</a></nav><h1><code>${esc(item.name)}</code></h1><p class="muted">${esc(item.description)}.</p><div class="demo">${shellDemo(item.name,item.example)}</div><section class="grid lesson-grid"><article class="card"><h2>What it teaches</h2><p>${esc(item.description)}. Exact options vary by distribution and implementation, so use the installed command's documentation for the full option set.</p></article><article class="card"><h2>Starter example</h2><pre>${esc(item.example)}</pre></article><article class="card"><h2>Practice</h2><p>Predict the result, run the command in the simulator, inspect stdout/stderr and check the exit status.</p><a class="cta" href="/beginner/?command=${encodeURIComponent(item.name)}">Open LinuxTerminal.me</a></article></section><section class="card section-gap"><h2>How it fits into Linux</h2><ol><li>The shell parses the command and arguments.</li><li>The command performs its operation and writes stdout/stderr.</li><li>The process returns an exit status used by scripts and conditionals.</li></ol><p>Need help? Use the contextual LinuxTerminal AI Tutor on the Beginner page.</p><a class="cta" href="/beginner/#tutor">Ask the AI Tutor</a></section></main></body></html>`;
}

export default async (request: Request) => {
  const pathname = new URL(request.url).pathname.replace(/\/+$/, '');
  const name = pathname === '/commands' ? '' : pathname.replace(/^\/commands\//, '');
  if (!name) return new Response(indexHtml(), { headers: { 'content-type': 'text/html; charset=UTF-8', 'cache-control': 'public,max-age=300' } });
  const item = byName.get(name);
  if (!item) return new Response('LinuxTerminal.me: command lesson not found.', { status: 404, headers: { 'content-type': 'text/plain; charset=utf-8' } });
  return new Response(lessonHtml(item), { headers: { 'content-type': 'text/html; charset=UTF-8', 'cache-control': 'public,max-age=300' } });
};

export const config = { path: '/commands/*' };
