const MODEL = Netlify.env.get('HF_MODEL') || 'google/gemma-2-2b-it';
const MAX_OUTPUT_TOKENS = 300;
const MAX_CONTEXT_CHARS = 5000;
const MAX_QUESTION_CHARS = 1200;
const WINDOW = 60_000;
const LIMIT = 12;
const TIMEOUT_MS = 15_000;
const buckets = new Map<string, { started: number; count: number }>();
const headers = () => ({ 'access-control-allow-origin': 'https://linuxterminal.me', 'access-control-allow-methods': 'POST, OPTIONS', 'access-control-allow-headers': 'content-type', 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store' });
const json = (body: Record<string, unknown>, status: number) => new Response(JSON.stringify(body), { status, headers: headers() });
function fallback(contextText: string, question: string): string { const lower = `${question}\n${contextText}`.toLowerCase(); if (lower.includes('command-not-found') || lower.includes('not found')) return 'That command was not found. Check spelling with `command -v <command>`, then verify that the lesson expects that tool.'; if (lower.includes('permission denied')) return 'Permission denied means the current user lacks the required permission. Inspect the target with `ls -l` and learn the ownership and mode before changing anything.'; if (lower.includes('pwd')) return '`pwd` prints your current working directory. Use it whenever you need to confirm where you are in the filesystem.'; if (lower.includes('ls')) return '`ls` lists directory entries. Try `ls -la` to include hidden entries and useful metadata.'; if (lower.includes('cd')) return '`cd` changes the current working directory. Try `cd /tmp`, then `pwd` to verify the change.'; if (lower.includes('mkdir')) return '`mkdir` creates directories. Start with `mkdir practice`, then use `cd practice` and `pwd` to verify it.'; if (lower.includes('cat')) return '`cat` writes a file to standard output. It is useful for short files and for learning how stdout flows through the shell.'; if (lower.includes('hint') || lower.includes('next')) return 'Start with the command you just ran, inspect its output and exit status, then make one small change. Compare the new result with your prediction.'; return 'Start by identifying the command, its arguments, the current directory, and the output or error. Make one small experiment and compare the result with your prediction.'; }
function clientKey(request: Request, context: any): string { const forwarded = request.headers.get('x-forwarded-for'); const trustedIp = context?.ip; if (typeof trustedIp === 'string' && trustedIp.trim()) return trustedIp.trim(); if (forwarded) return forwarded.split(',')[0]?.trim() || 'unknown'; return 'unknown'; }
export default async (request: Request, context: any) => {
  if (request.method === 'OPTIONS') return new Response('', { status: 204, headers: headers() });
  if (request.method !== 'POST') return json({ error: 'method not allowed' }, 405);
  const ip = clientKey(request, context); const now = Date.now(); const bucket = buckets.get(ip);
  if (!bucket || now - bucket.started >= WINDOW) buckets.set(ip, { started: now, count: 1 });
  else { bucket.count++; if (bucket.count > LIMIT) return json({ error: 'Tutor rate limit reached. Please wait a minute.' }, 429); }
  if (buckets.size > 10_000) { for (const [key, value] of buckets) if (now - value.started >= WINDOW) buckets.delete(key); }
  let body: any; try { body = await request.json(); } catch { return json({ error: 'Invalid JSON.' }, 400); }
  const question = String(body.question || '').trim().slice(0, MAX_QUESTION_CHARS); const contextText = String(body.context || '').trim().slice(0, MAX_CONTEXT_CHARS);
  if (!question) return json({ error: 'Question is required.' }, 400);
  const token = Netlify.env.get('HF_TOKEN'); if (!token) return json({ answer: fallback(contextText, question), model: 'LinuxTerminal-guided-tutor', limited: true }, 200);
  const prompt = ['You are LinuxTerminal Tutor, a concise Linux teacher.','Teach safely and accurately. Never execute commands, request secrets, or claim the browser sandbox is the host OS.','Use the learner context to explain the command, error, recent history and next safe practice step.','Prefer short explanations, concrete Linux concepts and one small practice step.','','Learner context:',contextText || '(no additional context)','','Question:',question].join('\n');
  const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), TIMEOUT_MS);
  try { const response = await fetch('https://router.huggingface.co/v1/chat/completions', { method:'POST', signal:controller.signal, headers:{authorization:`Bearer ${token}`,'content-type':'application/json'}, body:JSON.stringify({model:`${MODEL}:hf-inference`,messages:[{role:'system',content:'You are LinuxTerminal Tutor. Answer as a safe, concise Linux instructor.'},{role:'user',content:prompt}],max_tokens:MAX_OUTPUT_TOKENS,temperature:0.2,stream:false}) }); if (!response.ok) return json({ answer: fallback(contextText, question), model: 'LinuxTerminal-guided-tutor', limited: true }, 200); const data = await response.json(); const answer = data?.choices?.[0]?.message?.content; if (typeof answer !== 'string' || !answer.trim()) return json({ answer: fallback(contextText, question), model: 'LinuxTerminal-guided-tutor', limited: true }, 200); return json({ answer: answer.trim().slice(0, 5000), model: MODEL, provider: 'hf-inference' }, 200); } catch (error) { console.error('Tutor request failed', error instanceof Error ? error.message : String(error)); return json({ answer: fallback(contextText, question), model: 'LinuxTerminal-guided-tutor', limited: true }, 200); } finally { clearTimeout(timeout); }
};
