import './core/verified-iso-fetch.ts';
import './v86-telemetry.ts';
import { V86LinuxTerminal } from './main-v86.ts';

declare global {
  interface Window {
    linuxLabVM?: V86LinuxTerminal;
  }
}

/**
 * main-v86.ts owns VM construction. This entry module only normalizes the
 * runtime constructor name and hardens the view-switching path before the
 * DOMContentLoaded handler creates the VM.
 */
function exposeV86Constructor(): void {
  const win = window as Window & {
    V86Starter?: new (options: Record<string, unknown>) => unknown;
    V86?: new (options: Record<string, unknown>) => unknown;
  };

  if (typeof win.V86Starter === 'function' && typeof win.V86 !== 'function') {
    Object.defineProperty(win, 'V86', {
      configurable: true,
      writable: true,
      value: win.V86Starter,
    });
  }
}

/**
 * Screen toggling must only change visibility. The old showScreen() called
 * fit(), and fit() could dispatch a synthetic resize while the screen was
 * visible. That resize re-entered the resize listener, which called fit()
 * again. Under Chromium/v86 this feedback path could monopolize the event
 * loop and make Playwright's screen-toggle stage wait for 20 seconds.
 *
 * Do not resize xterm while switching to the VGA screen. The terminal is
 * hidden at that point, so fitting it is unnecessary. showTerminal() still
 * performs the normal fit when the terminal becomes visible again.
 */
function makeScreenToggleNonBlocking(): void {
  const prototype = V86LinuxTerminal.prototype as unknown as {
    showScreen?: () => void;
    fit?: () => void;
  };

  if (typeof prototype.showScreen !== 'function') return;

  prototype.showScreen = function showScreenWithoutFit(): void {
    const screen = document.getElementById('screen_container');
    const terminal = document.getElementById('v86-terminal-container');
    if (screen) screen.hidden = false;
    if (terminal) terminal.hidden = true;
  };

  // Keep direct resize handling safe as well. Real browser resize events still
  // fit xterm, but no synthetic resize is generated by the guarded path.
  if (typeof prototype.fit === 'function') {
    prototype.fit = function guardedFit(this: V86LinuxTerminal): void {
      try {
        const instance = this as unknown as {
          fitAddon?: { fit?: () => void };
        };
        instance.fitAddon?.fit?.();
      } catch {
        // Layout fitting is best-effort.
      }
    };
  }
}

exposeV86Constructor();
makeScreenToggleNonBlocking();

// main-v86.ts owns VM construction. Do not instantiate V86LinuxTerminal here.
void V86LinuxTerminal;
